const SHEETS = {
  SETTINGS: 'Settings', PROJECTS: 'Projects', OBJECTIVES: 'Objectives', ACTIVITIES: 'Activities',
  INDICATORS: 'Indicators', BENEFICIARIES: 'Beneficiaries', FOLLOWUPS: 'FollowUps',
  EVIDENCE: 'Evidence', LESSONS: 'Lessons', CHALLENGES: 'Challenges', REPORTS: 'Reports', USERS: 'Users'
};

const HEADERS = {
  Settings: ['Key','Value'],
  Projects: ['Project ID','Project Name','Code','Description','Start Date','End Date','Status','Budget','Currency','Communities','Partners','Responsible Person','Created At'],
  Objectives: ['Objective ID','Project ID','Objective','Description','Created At'],
  Activities: ['Activity ID','Project ID','Objective ID','Activity','Community','Start Date','End Date','Status','Responsible Person','Budget','Actual Cost','Notes'],
  Indicators: ['Indicator ID','Project ID','Objective ID','Indicator','Definition','Type','Baseline','Target','Current Achievement','Unit','Data Source','Frequency','Responsible Person','Last Updated'],
  Beneficiaries: ['Beneficiary ID','Project ID','Full Name','Sex','Date of Birth','Age','Community','County','Phone','Guardian Name','School','School Status','Reason OOSC','Consent','Current Stage','Enrollment Date','Household Empowered','Retention Status','Completion Date','Story','Photo URL','Created At','Updated At'],
  FollowUps: ['FollowUp ID','Beneficiary ID','Project ID','Date','Stage','School Status','Retention Status','Household Status','Notes','Action Required','Officer','Next FollowUp'],
  Evidence: ['Evidence ID','Project ID','Activity ID','Indicator ID','Beneficiary ID','Date','Evidence Type','Description','Drive URL','Collected By'],
  Lessons: ['Lesson ID','Project ID','Date','Lesson','What Worked','What Did Not Work','Recommendation','Recorded By'],
  Challenges: ['Challenge ID','Project ID','Date','Challenge','Impact','Action Taken','Recommendation','Status','Responsible Person'],
  Reports: ['Report ID','Project ID','Report Type','Period Start','Period End','Generated At','Generated By','Drive URL'],
  Users: ['User ID','Name','Email','Role','Project Access','Status']
};

function setupUAFMEL() {
  const ss = SpreadsheetApp.getActive();
  Object.keys(HEADERS).forEach(name => {
    let sh = ss.getSheetByName(name) || ss.insertSheet(name);
    if (sh.getLastRow() === 0) sh.appendRow(HEADERS[name]);
    else sh.getRange(1,1,1,HEADERS[name].length).setValues([HEADERS[name]]);
    sh.setFrozenRows(1);
  });
  const settings = ss.getSheetByName('Settings');
  settings.getRange(2,1,5,2).setValues([
    ['Organization','Upskill Africa Foundation'],
    ['System Name','UAF Digital M&E/L System'],
    ['Version','1.0'],
    ['Default Currency','USD'],
    ['Beneficiary Journey','Identified → Verified → Referred → Enrolled → Household Empowered → Follow-up → Retained → Completed']
  ]);
}

function doGet(e) {
  return ContentService.createTextOutput(JSON.stringify({ok:true,system:'UAF Digital M&E/L',version:'1.0'})).setMimeType(ContentService.MimeType.JSON);
}
