/* UAF STAGE 16 — KNOWLEDGE MANAGEMENT, LESSONS, LEARNING & ORGANIZATIONAL IMPROVEMENT M&E */
var STAGE16_HEADERS={
 KnowledgeAssets:['Asset ID','Project ID','Asset Type','Title','Description','Topic','Author','Date Created','Source','Evidence URL','Document URL','Status','Access Level','Tags','Created At','Updated At'],
 LearningQuestions:['Learning Question ID','Project ID','Question','Why It Matters','Evidence Needed','Owner','Review Date','Status','Answer','Evidence URL','Created At','Updated At'],
 LearningSessions:['Session ID','Project ID','Date','Session Type','Topic','Objective','Participants','Facilitator','Key Insights','Decisions','Actions','Evidence URL','Status','Created At'],
 LessonsLearned:['Lesson ID','Project ID','Date','Theme','Lesson','Context','Evidence','What Worked','What Did Not Work','Recommendation','Responsible Person','Status','Evidence URL','Created At'],
 AdaptationActions:['Adaptation ID','Project ID','Date','Problem','Evidence','Adaptation','Expected Result','Actual Result','Decision','Owner','Due Date','Status','Evidence URL','Created At'],
 GoodPractices:['Practice ID','Project ID','Date','Practice','Why It Works','Evidence','Applicable Context','Replicable','Owner','Status','Evidence URL','Created At'],
 KnowledgeProducts:['Product ID','Project ID','Product Type','Title','Audience','Purpose','Key Message','Source Evidence','Publication Date','Publication URL','Status','Owner','Created At'],
 ImprovementActions:['Improvement ID','Project ID','Date','Improvement Area','Issue','Root Cause','Action','Owner','Due Date','Baseline','Target','Actual','Status','Evidence URL','Created At'],
 OrganizationalDecisions:['Decision ID','Project ID','Date','Decision','Evidence','Reason','Responsible Person','Due Date','Status','Outcome','Evidence URL','Created At'],
 KMReviews:['Review ID','Project ID','Review Period','Knowledge Generated','Knowledge Used','Lessons Recorded','Adaptations Completed','Improvement Actions Completed','Learning Rate %','Review Summary','Reviewer','Review Date','Status'],
 LearningAlerts:['Learning Alert ID','Project ID','Alert Type','Severity','Message','Status','Due Date','Assigned To','Created At']
};
function setupStage16(){var ss=SpreadsheetApp.getActive();Object.keys(STAGE16_HEADERS).forEach(function(n){var s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()==0)s.appendRow(STAGE16_HEADERS[n]);s.setFrozenRows(1);});var s=ss.getSheetByName('Settings');if(s){var d={'Stage 16':'Knowledge Management, Lessons, Learning & Organizational Improvement M&E','Learning Cycle':'Question → Evidence → Learn → Adapt → Implement → Review → Institutionalize','Knowledge Model':'Capture → Organize → Share → Use → Improve'};var old=rows_('Settings');Object.keys(d).forEach(function(k){if(!old.some(function(x){return x.Key==k;}))s.appendRow([k,d[k]]);});}return 'Stage 16 setup complete; existing data preserved.';}
function s16Rows_(name,pid){return rows_(name).filter(function(x){return !pid||String(x['Project ID']||'')===String(pid);});}
function s16n_(v){var n=Number(v);return isNaN(n)?0:n;}
function stage16Dashboard_(pid){permission_('read',pid||'');var a=s16Rows_('KnowledgeAssets',pid),q=s16Rows_('LearningQuestions',pid),s=s16Rows_('LearningSessions',pid),l=s16Rows_('LessonsLearned',pid),ad=s16Rows_('AdaptationActions',pid),g=s16Rows_('GoodPractices',pid),kp=s16Rows_('KnowledgeProducts',pid),ia=s16Rows_('ImprovementActions',pid),d=s16Rows_('OrganizationalDecisions',pid),r=s16Rows_('KMReviews',pid),al=s16Rows_('LearningAlerts',pid);var openQ=q.filter(function(x){return !['completed','closed','answered'].includes(String(x.Status||'').toLowerCase());}).length;var completedAdapt=ad.filter(function(x){return ['completed','implemented','closed'].includes(String(x.Status||'').toLowerCase());}).length;var completedImprove=ia.filter(function(x){return ['completed','implemented','closed'].includes(String(x.Status||'').toLowerCase());}).length;var overdue=ad.concat(ia).filter(function(x){return x['Due Date']&&new Date(x['Due Date'])<new Date()&&!['completed','implemented','closed'].includes(String(x.Status||'').toLowerCase());}).length;var latest=r.length?r[r.length-1]:null;return {summary:{knowledgeAssets:a.length,openLearningQuestions:openQ,learningSessions:s.length,lessonsLearned:l.length,adaptations:ad.length,adaptationsCompleted:completedAdapt,goodPractices:g.length,knowledgeProducts:kp.length,improvementActions:ia.length,improvementActionsCompleted:completedImprove,decisions:d.length,overdueActions:overdue,openAlerts:al.filter(function(x){return String(x.Status||'Open').toLowerCase()!=='resolved';}).length,latestLearningRate:latest?s16n_(latest['Learning Rate %']):0},knowledgeAssets:a,learningQuestions:q,sessions:s,lessons:l,adaptations:ad,goodPractices:g,knowledgeProducts:kp,improvements:ia,decisions:d,alerts:al.filter(function(x){return String(x.Status||'Open').toLowerCase()!=='resolved';})};}
function stage16Validate_(entity,d){if(['knowledgeAsset','learningQuestion','learningSession','lesson','goodPractice','knowledgeProduct','improvementAction','decision'].indexOf(entity)>=0&&!d['Project ID']&&!d.projectId)throw Error('Project ID is required.');if(entity==='knowledgeAsset'&&!String(d.Title||'').trim())throw Error('Knowledge asset title is required.');if(entity==='learningQuestion'&&!String(d.Question||'').trim())throw Error('Learning question is required.');if(entity==='lesson'&&!String(d.Lesson||'').trim())throw Error('Lesson is required.');}
function createStage16Record_(entity,data){var map={knowledgeAsset:'KnowledgeAssets',learningQuestion:'LearningQuestions',learningSession:'LearningSessions',lesson:'LessonsLearned',adaptation:'AdaptationActions',goodPractice:'GoodPractices',knowledgeProduct:'KnowledgeProducts',improvementAction:'ImprovementActions',decision:'OrganizationalDecisions',kmReview:'KMReviews',learningAlert:'LearningAlerts'},sheet=map[entity];if(!sheet)throw Error('Unsupported Stage 16 entity');var pid=data['Project ID']||data.projectId||'';permission_('create',pid);stage16Validate_(entity,data);var s=SpreadsheetApp.getActive().getSheetByName(sheet),h=STAGE16_HEADERS[sheet],prefix={knowledgeAsset:'KAS',learningQuestion:'LQ',learningSession:'SES',lesson:'LES',adaptation:'ADP',goodPractice:'GPR',knowledgeProduct:'KNP',improvementAction:'IMP',decision:'DEC',kmReview:'KMR',learningAlert:'LAL'}[entity],id=id_(prefix),now=new Date();s.appendRow(h.map(function(k){if(k==='Created At'||k==='Updated At')return now;if(/ID$/.test(k)&&!data[k])return id;return data[k]!==undefined?data[k]:'';}));audit_('CREATE',entity,id,data);return json_({ok:true,id:id});}
function stage16GenerateAlerts_(pid){permission_('update',pid||'');var s=SpreadsheetApp.getActive().getSheetByName('LearningAlerts'),created=0,today=new Date();s16Rows_('LearningQuestions',pid).forEach(function(x){if(x['Review Date']&&new Date(x['Review Date'])<today&&!['completed','closed','answered'].includes(String(x.Status||'').toLowerCase())){s.appendRow([id_('LAL'),pid,'LEARNING_QUESTION_OVERDUE','Amber','Learning question review is overdue: '+x.Question,'Open',x['Review Date'],x.Owner,today]);created++;}});s16Rows_('AdaptationActions',pid).concat(s16Rows_('ImprovementActions',pid)).forEach(function(x){if(x['Due Date']&&new Date(x['Due Date'])<today&&!['completed','implemented','closed'].includes(String(x.Status||'').toLowerCase())){s.appendRow([id_('LAL'),pid,'ACTION_OVERDUE','High','Learning/improvement action is overdue.','Open',x['Due Date'],x.Owner,today]);created++;}});return json_({ok:true,created:created});}
function stage16GetAction_(a){return ['stage16','knowledgeDashboard','knowledgeAssets','learningQuestions','learningSessions','lessonsLearned','adaptationActions','goodPractices','knowledgeProducts','improvementActions','organizationalDecisions','kmReviews','learningAlerts'].indexOf(a)>=0;}
function stage16Get_(a,e){var pid=e&&e.parameter?e.parameter.projectId||'':'';if(a==='stage16'||a==='knowledgeDashboard')return json_({ok:true,data:stage16Dashboard_(pid)});var map={knowledgeAssets:'KnowledgeAssets',learningQuestions:'LearningQuestions',learningSessions:'LearningSessions',lessonsLearned:'LessonsLearned',adaptationActions:'AdaptationActions',goodPractices:'GoodPractices',knowledgeProducts:'KnowledgeProducts',improvementActions:'ImprovementActions',organizationalDecisions:'OrganizationalDecisions',kmReviews:'KMReviews',learningAlerts:'LearningAlerts'},n=map[a];permission_('read',pid);return json_({ok:true,data:s16Rows_(n,pid)});}
function stage16PostAction_(a){return ['stage16Setup','createStage16Record','generateLearningAlerts'].indexOf(a)>=0;}
function stage16Post_(a,d){if(a==='stage16Setup'){permission_('update');return json_({ok:true,message:setupStage16()});}if(a==='createStage16Record')return createStage16Record_(d.entity,d.data||{});if(a==='generateLearningAlerts')return stage16GenerateAlerts_(d.projectId||'');}
