/* UAF STAGE 19 — GENDER EQUALITY, EQUITY, DISABILITY & SOCIAL INCLUSION M&E */
var STAGE19_HEADERS={
 GEDIPolicies:['Policy ID','Policy Type','Title','Version','Effective Date','Review Date','Owner','Status','Document URL','Created At'],
 GEDIIndicators:['Indicator ID','Project ID','Theme','Indicator','Definition','Disaggregation','Baseline','Target','Current Achievement','Unit','Frequency','Data Source','Owner','Status','Last Updated'],
 InclusionAssessments:['Assessment ID','Project ID','Date','Activity/Area','Gender Inclusion','Disability Inclusion','Child Inclusion','Economic Inclusion','Geographic Inclusion','Other Vulnerability Inclusion','Overall Score','Gaps','Actions Required','Reviewer','Status','Evidence URL','Created At'],
 GenderAnalysis:['Analysis ID','Project ID','Date','Issue/Barrier','Affected Group','Evidence','Impact','Root Cause','Recommended Action','Owner','Status','Evidence URL','Created At'],
 DisabilityInclusion:['Record ID','Project ID','Date','Barrier Type','Affected Group','Accessibility Need','Accommodation/Adjustment','Provided','Cost','Owner','Status','Evidence URL','Created At'],
 InclusionBeneficiaries:['Record ID','Project ID','Beneficiary ID','Gender','Age Group','Disability Status','Disability Type','Location','Vulnerability Group','Participation Level','Support Received','Outcome','Created At'],
 ParticipationEquity:['Participation ID','Project ID','Date','Activity','Target Group','Invited','Participated','Decision Making','Leadership','Participation Rate','Equity Gap','Action Required','Status','Created At'],
 SafeguardingInclusion:['Check ID','Project ID','Date','Activity ID','Inclusion Standard','Result','Barrier/Risk','Corrective Action','Owner','Due Date','Status','Evidence URL','Created At'],
 InclusionActions:['Action ID','Project ID','Date','Inclusion Area','Issue','Action','Owner','Due Date','Status','Completion Date','Evidence URL','Created At'],
 GEDICommitments:['Commitment ID','Project ID','Stakeholder','Commitment','Inclusion Area','Due Date','Status','Completion Date','Evidence URL','Owner','Created At'],
 InclusionComplaints:['Complaint ID','Project ID','Date','Channel','Inclusion Category','Complaint/Feedback','Anonymous','Risk Level','Action Required','Owner','Status','Response Date','Evidence URL','Created At'],
 GEDIAlerts:['Alert ID','Project ID','Alert Type','Severity','Message','Status','Due Date','Assigned To','Created At']
};
function setupStage19(){var ss=SpreadsheetApp.getActive();Object.keys(STAGE19_HEADERS).forEach(function(n){var s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()==0)s.appendRow(STAGE19_HEADERS[n]);s.setFrozenRows(1);});var s=ss.getSheetByName('Settings');if(s){var d={'Stage 19':'Gender Equality, Equity, Disability & Social Inclusion M&E','GEDI Principle':'Equal access, meaningful participation, non-discrimination, accessibility, equity and inclusion','Inclusion Cycle':'Assess → Disaggregate → Identify Barriers → Adapt → Participate → Measure → Improve'};var old=rows_('Settings');Object.keys(d).forEach(function(k){if(!old.some(function(x){return x.Key==k;}))s.appendRow([k,d[k]]);});}return 'Stage 19 setup complete; existing data preserved.';}
function s19Rows_(n,pid){return rows_(n).filter(function(x){return !pid||String(x['Project ID']||'')===String(pid);});}
function s19n_(v){var n=Number(v);return isNaN(n)?0:n;}
function stage19Dashboard_(pid){permission_('read',pid||'');var pol=rows_('GEDIPolicies'),gi=s19Rows_('GEDIIndicators',pid),ia=s19Rows_('InclusionAssessments',pid),ga=s19Rows_('GenderAnalysis',pid),di=s19Rows_('DisabilityInclusion',pid),ib=s19Rows_('InclusionBeneficiaries',pid),pe=s19Rows_('ParticipationEquity',pid),sp=s19Rows_('SafeguardingInclusion',pid),ac=s19Rows_('InclusionActions',pid),co=s19Rows_('GEDICommitments',pid),cp=s19Rows_('InclusionComplaints',pid),al=s19Rows_('GEDIAlerts',pid);var avg=ia.length?Math.round(ia.reduce(function(a,x){return a+s19n_(x['Overall Score']);},0)/ia.length*100)/100:0;var checks=sp.length,passes=sp.filter(function(x){return ['pass','compliant','yes'].indexOf(String(x.Result||'').toLowerCase())>=0;}).length;var compliance=checks?Math.round(passes/checks*10000)/100:0;var actionsOpen=ac.filter(function(x){return !['completed','closed'].includes(String(x.Status||'').toLowerCase());}).length;var complaintsOpen=cp.filter(function(x){return !['resolved','closed'].includes(String(x.Status||'').toLowerCase());}).length;var alerts=al.filter(function(x){return !['resolved','closed'].includes(String(x.Status||'').toLowerCase());}).length;return {summary:{policies:pol.length,indicators:gi.length,assessments:ia.length,inclusionScore:avg,genderAnalyses:ga.length,disabilityRecords:di.length,beneficiaryRecords:ib.length,participationRecords:pe.length,safeguardingChecks:checks,inclusionCompliance:compliance,openActions:actionsOpen,commitments:co.length,openComplaints:complaintsOpen,openAlerts:alerts},policies:pol,indicators:gi,assessments:ia,gender:ga,disability:di,beneficiaries:ib,participation:pe,safeguarding:sp,actions:ac,commitments:co,complaints:cp,alerts:al.filter(function(x){return !['resolved','closed'].includes(String(x.Status||'').toLowerCase());})};}
function stage19Validate_(entity,d){var req=['gediIndicator','inclusionAssessment','genderAnalysis','disabilityInclusion','inclusionBeneficiary','participationEquity','safeguardingInclusion','inclusionAction','gediCommitment','inclusionComplaint'];if(req.indexOf(entity)>=0&&!d['Project ID']&&!d.projectId)throw Error('Project ID is required.');if(entity==='gediIndicator'&&!String(d.Indicator||'').trim())throw Error('GEDI indicator is required.');}
function createStage19Record_(entity,data){var map={gediPolicy:'GEDIPolicies',gediIndicator:'GEDIIndicators',inclusionAssessment:'InclusionAssessments',genderAnalysis:'GenderAnalysis',disabilityInclusion:'DisabilityInclusion',inclusionBeneficiary:'InclusionBeneficiaries',participationEquity:'ParticipationEquity',safeguardingInclusion:'SafeguardingInclusion',inclusionAction:'InclusionActions',gediCommitment:'GEDICommitments',inclusionComplaint:'InclusionComplaints',gediAlert:'GEDIAlerts'},sheet=map[entity];if(!sheet)throw Error('Unsupported Stage 19 entity');var pid=data['Project ID']||data.projectId||'';permission_('create',pid);stage19Validate_(entity,data);var s=SpreadsheetApp.getActive().getSheetByName(sheet),h=STAGE19_HEADERS[sheet],prefix={gediPolicy:'GEP',gediIndicator:'GEI',inclusionAssessment:'IAS',genderAnalysis:'GAN',disabilityInclusion:'DIS',inclusionBeneficiary:'IBN',participationEquity:'PAR',safeguardingInclusion:'SIC',inclusionAction:'IAC',gediCommitment:'GEC',inclusionComplaint:'ICP',gediAlert:'GAL'}[entity],id=id_(prefix),now=new Date();s.appendRow(h.map(function(k){if(k==='Created At'||k==='Updated At')return now;if(/ID$/.test(k)&&!data[k])return id;return data[k]!==undefined?data[k]:'';}));audit_('CREATE',entity,id,data);return json_({ok:true,id:id});}
function stage19GenerateAlerts_(pid){permission_('update',pid||'');var s=SpreadsheetApp.getActive().getSheetByName('GEDIAlerts'),now=new Date(),created=0;function add(type,sev,msg,due,owner){s.appendRow([id_('GAL'),pid,type,sev,msg,'Open',due||'',owner||'',now]);created++;}s19Rows_('InclusionAssessments',pid).forEach(function(x){if(s19n_(x['Overall Score'])<60)add('LOW_INCLUSION_SCORE','High','Inclusion assessment score is below 60%. Adaptation is required.',x['Review Date'],x.Reviewer);});s19Rows_('SafeguardingInclusion',pid).forEach(function(x){if(['fail','no','non-compliant'].includes(String(x.Result||'').toLowerCase()))add('SAFEGUARDING_INCLUSION_GAP','High','Safeguarding/inclusion check identified a gap.',x['Due Date'],x.Owner);});s19Rows_('InclusionActions',pid).forEach(function(x){if(x['Due Date']&&new Date(x['Due Date'])<now&&!['completed','closed'].includes(String(x.Status||'').toLowerCase()))add('INCLUSION_ACTION_OVERDUE','Amber','Inclusion corrective action is overdue.',x['Due Date'],x.Owner);});s19Rows_('InclusionComplaints',pid).forEach(function(x){if(['high','critical'].includes(String(x['Risk Level']||'').toLowerCase())&&!['resolved','closed'].includes(String(x.Status||'').toLowerCase()))add('HIGH_INCLUSION_COMPLAINT','Critical','High-risk inclusion complaint requires prompt response.',x['Response Date'],x.Owner);});return json_({ok:true,created:created});}
function stage19GetAction_(a){return ['stage19','gediDashboard','gediPolicies','gediIndicators','inclusionAssessments','genderAnalysis','disabilityInclusion','inclusionBeneficiaries','participationEquity','safeguardingInclusion','inclusionActions','gediCommitments','inclusionComplaints','gediAlerts'].indexOf(a)>=0;}
function stage19Get_(a,e){var pid=e&&e.parameter?e.parameter.projectId||'':'';if(a==='stage19'||a==='gediDashboard')return json_({ok:true,data:stage19Dashboard_(pid)});var map={gediPolicies:'GEDIPolicies',gediIndicators:'GEDIIndicators',inclusionAssessments:'InclusionAssessments',genderAnalysis:'GenderAnalysis',disabilityInclusion:'DisabilityInclusion',inclusionBeneficiaries:'InclusionBeneficiaries',participationEquity:'ParticipationEquity',safeguardingInclusion:'SafeguardingInclusion',inclusionActions:'InclusionActions',gediCommitments:'GEDICommitments',inclusionComplaints:'InclusionComplaints',gediAlerts:'GEDIAlerts'},n=map[a];permission_('read',pid);return json_({ok:true,data:s19Rows_(n,pid)});}
function stage19PostAction_(a){return ['stage19Setup','createStage19Record','generateGEDIAlerts'].indexOf(a)>=0;}
function stage19Post_(a,d){if(a==='stage19Setup'){permission_('update');return json_({ok:true,message:setupStage19()});}if(a==='createStage19Record')return createStage19Record_(d.entity,d.data||{});if(a==='generateGEDIAlerts')return stage19GenerateAlerts_(d.projectId||'');}
