// UAF Digital M&E/L — Stage 8: Data Quality & M&E Governance
const STAGE8_HEADERS={
DataQualityChecks:['Check ID','Project ID','Entity','Record ID','Check Type','Field','Issue','Severity','Status','Assigned To','Checked By','Checked At','Resolution','Resolved At'],
VerificationQueue:['Verification ID','Project ID','Entity','Record ID','Verification Type','Submitted By','Submitted At','Verifier','Verified At','Status','Comments'],
DataCorrections:['Correction ID','Project ID','Entity','Record ID','Field','Old Value','New Value','Reason','Requested By','Requested At','Approved By','Approved At','Status'],
DataQualityScores:['Score ID','Project ID','Period','Completeness %','Validity %','Consistency %','Timeliness %','Uniqueness %','Overall Score %','RAG','Calculated At'],
GovernanceActions:['Governance ID','Project ID','Date','Action Type','Issue','Decision','Responsible Person','Due Date','Status','Evidence URL','Notes'],
};
function setupStage8(){var ss=SpreadsheetApp.getActive();Object.keys(STAGE8_HEADERS).forEach(function(n){var s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()==0)s.appendRow(STAGE8_HEADERS[n]);s.setFrozenRows(1);});var s=ss.getSheetByName('Settings');var defaults={'Stage 8':'Data quality, verification, correction workflow and M&E governance','Data Quality Standard':'Completeness, validity, consistency, timeliness and uniqueness','Verification Model':'Field submission → verification queue → approved record'};var old=rows_('Settings');Object.keys(defaults).forEach(function(k){if(!old.some(function(x){return x.Key==k;}))s.appendRow([k,defaults[k]]);});return 'Stage 8 setup complete; existing data preserved.';}
function stage8Visible_(sheet,projectId){return rows_(sheet).filter(function(x){return !x['Project ID']||projectAllowed_(x['Project ID']);}).filter(function(x){return !projectId||String(x['Project ID'])==String(projectId);});}
function stage8Quality_(projectId){var b=stage8Visible_('Beneficiaries',projectId),i=stage8Visible_('Indicators',projectId),f=stage8Visible_('FollowUps',projectId),e=stage8Visible_('Evidence',projectId),issues=[];b.forEach(function(x){[['Full Name',x['Full Name']],['Project ID',x['Project ID']],['Consent',x.Consent],['Community',x.Community],['Current Stage',x['Current Stage']]].forEach(function(q){if(String(q[1]||'').trim()==='')issues.push({entity:'Beneficiary',id:x['Beneficiary ID'],type:'Missing Required Field',field:q[0],severity:'High'});});if(String(x.Consent).toLowerCase()!='yes')issues.push({entity:'Beneficiary',id:x['Beneficiary ID'],type:'Consent Validation',field:'Consent',severity:'Critical'});});i.forEach(function(x){if(Number(x.Target)<0||isNaN(Number(x.Target)))issues.push({entity:'Indicator',id:x['Indicator ID'],type:'Invalid Target',field:'Target',severity:'High'});if(Number(x['Current Achievement'])<0||isNaN(Number(x['Current Achievement'])))issues.push({entity:'Indicator',id:x['Indicator ID'],type:'Invalid Achievement',field:'Current Achievement',severity:'High'});});var seen={};b.forEach(function(x){var key=(String(x['Full Name']).trim().toLowerCase()+'|'+String(x.Community).trim().toLowerCase());if(key!='|'){if(seen[key])issues.push({entity:'Beneficiary',id:x['Beneficiary ID'],type:'Possible Duplicate',field:'Full Name + Community',severity:'Medium'});seen[key]=x['Beneficiary ID'];}});f.forEach(function(x){if(x.NextFollowUp&&new Date(x.NextFollowUp)<new Date()&&String(x.Status||'').toLowerCase()!='resolved')issues.push({entity:'FollowUp',id:x['FollowUp ID'],type:'Overdue Follow-up',field:'NextFollowUp',severity:'Medium'});});var total=b.length*5,missing=issues.filter(function(x){return x.type=='Missing Required Field';}).length,validityIssues=issues.filter(function(x){return ['Consent Validation','Invalid Target','Invalid Achievement'].indexOf(x.type)>=0;}).length,duplicates=issues.filter(function(x){return x.type=='Possible Duplicate';}).length;var completeness=total?Math.max(0,100-missing/Math.max(1,b.length*5)*100):100;var validity=total?Math.max(0,100-validityIssues/Math.max(1,b.length+i.length)*100):100;var uniqueness=b.length?Math.max(0,100-duplicates/b.length*100):100;var timeliness=f.length?Math.max(0,100-f.filter(function(x){return x.NextFollowUp&&new Date(x.NextFollowUp)<new Date();}).length/f.length*100):100;var consistency=e.length?100:80;var overall=Math.round((completeness+validity+consistency+timeliness+uniqueness)/5*100)/100;return {summary:{beneficiaries:b.length,indicators:i.length,followUps:f.length,evidence:e.length,issues:issues.length,critical:issues.filter(function(x){return x.severity=='Critical';}).length,high:issues.filter(function(x){return x.severity=='High';}).length,overallScore:overall,RAG:overall>=90?'Green':overall>=75?'Amber':'Red'},issues:issues};}
function stage8Dashboard_(projectId){var q=stage8Quality_(projectId),v=stage8Visible_('VerificationQueue',projectId),c=stage8Visible_('DataCorrections',projectId),g=stage8Visible_('GovernanceActions',projectId);return {quality:q,verification:{total:v.length,pending:v.filter(function(x){return String(x.Status).toLowerCase()=='pending';}).length,verified:v.filter(function(x){return String(x.Status).toLowerCase()=='verified';}).length},corrections:{total:c.length,pending:c.filter(function(x){return String(x.Status).toLowerCase()=='pending';}).length,approved:c.filter(function(x){return String(x.Status).toLowerCase()=='approved';}).length},governance:{total:g.length,open:g.filter(function(x){return String(x.Status).toLowerCase()!='completed';}).length}};}
function stage8CalculateScore_(projectId,period){var q=stage8Quality_(projectId),s=SpreadsheetApp.getActive().getSheetByName('DataQualityScores'),id=id_('DQS'),now=new Date(),overall=q.summary.overallScore,rag=q.summary.RAG;s.appendRow([id,projectId||'',period||Utilities.formatDate(now,Session.getScriptTimeZone(),'yyyy-MM'),q.summary.overallScore,q.summary.overallScore,q.summary.overallScore,q.summary.overallScore,q.summary.overallScore,overall,rag,now]);return {id:id,score:overall,RAG:rag};}
function createStage8Record_(entity,data){var map={qualityCheck:'DataQualityChecks',verification:'VerificationQueue',correction:'DataCorrections',qualityScore:'DataQualityScores',governance:'GovernanceActions'};var n=map[entity];if(!n)throw Error('Unsupported Stage 8 entity');var s=SpreadsheetApp.getActive().getSheetByName(n),h=STAGE8_HEADERS[n],o=data||{},id=id_('S8');var p=o['Project ID']||o.ProjectId||'';if(p)permission_('create',p);s.appendRow(h.map(function(k){if(k.indexOf('ID')>=0&&k!=='Project ID'&&k!=='Record ID')return o[k]||id;if(k==='Checked At'||k==='Submitted At'||k==='Requested At'||k==='Calculated At'||k==='Date')return o[k]||new Date();return o[k]!==undefined?o[k]:'';}));audit_('CREATE',entity,id,o);return json_({ok:true,id:id});}
function stage8GetAction_(a){return ['stage8','dataQuality','verificationQueue','corrections','governanceActions','qualityScore'].indexOf(a)>=0;}
function stage8Get_(a,e){permission_('read');var p=e&&e.parameter?e.parameter.projectId||'':'';if(a==='stage8')return json_(Object.assign({ok:true},stage8Dashboard_(p)));if(a==='dataQuality')return json_(Object.assign({ok:true},stage8Quality_(p)));var map={verificationQueue:'VerificationQueue',corrections:'DataCorrections',governanceActions:'GovernanceActions',qualityScore:'DataQualityScores'};return json_({ok:true,data:stage8Visible_(map[a],p)});}
function stage8PostAction_(a){return ['stage8Setup','createStage8Record','calculateQualityScore'].indexOf(a)>=0;}
// UAF_STAGE8_REFINED_SCORE
function stage8RefinedScoreAction_(a){return a==='calculateRefinedQualityScore';}
// UAF_STAGE8_REFINED_POST_ROUTE
function stage8Post_(a,d){if(stage8RefinedScoreAction_(a))return stage8RefinedScorePost_(d);if(a==='stage8Setup'){permission_('update');return json_({ok:true,message:setupStage8()});}if(a==='calculateQualityScore'){permission_('report',d.projectId||'');return json_({ok:true,data:stage8CalculateScore_(d.projectId||'',d.period||'')});}permission_('create',d.data&&d.data['Project ID']);return createStage8Record_(d.entity,d.data);}
function stage8RefinedScorePost_(d){permission_('report',d.projectId||'');return json_({ok:true,data:calculateRefinedQualityScore_(d.projectId||'',d.period||'')});}
