/* UAF M&E/L STAGE 9 — Advanced Analytics & Decision Support */
var STAGE9_HEADERS={
  Forecasts:['Forecast ID','Project ID','Indicator ID','Period','Current Achievement','Target','Projected Achievement','Projected %','Forecast RAG','Method','Calculated At'],
  DecisionSignals:['Signal ID','Project ID','Signal Type','Severity','Metric','Current Value','Threshold','Message','Recommended Action','Status','Created At']
};

function setupStage9(){
  Object.keys(STAGE9_HEADERS).forEach(function(s){var sh=SpreadsheetApp.getActive().getSheetByName(s);if(!sh){sh=SpreadsheetApp.getActive().insertSheet(s);sh.getRange(1,1,1,STAGE9_HEADERS[s].length).setValues([STAGE9_HEADERS[s]]);}});
  var ss=SpreadsheetApp.getActive(),cfg=ss.getSheetByName(SHEETS.SETTINGS);if(cfg){var r=cfg.getDataRange().getValues();var m={};r.slice(1).forEach(function(x){m[x[0]]=x[1]});if(!m['Stage 9'])cfg.appendRow(['Stage 9','Advanced analytics, forecasting and management decision support']);}
  return json_({ok:true,stage:'9',message:'Stage 9 initialized'});
}
function stage9Rows_(sheet){var sh=SpreadsheetApp.getActive().getSheetByName(sheet);if(!sh||sh.getLastRow()<2)return[];return rows_(sh.getDataRange().getValues());}
function stage9Portfolio_(){
  var p=stage9Rows_(SHEETS.PROJECTS),b=stage9Rows_(SHEETS.BENEFICIARIES),i=stage9Rows_(SHEETS.INDICATORS),f=stage9Rows_(SHEETS.FOLLOWUPS),g=stage9Rows_('Grants'),d=stage9Rows_('ReportingDeadlines'),q=stage9Rows_('DataQualityScores');
  var out=p.filter(function(x){return projectAllowed_(x['Project ID']);}).map(function(x){var id=x['Project ID'],bb=b.filter(function(z){return z['Project ID']===id}),ii=i.filter(function(z){return z['Project ID']===id}),ff=f.filter(function(z){return z['Project ID']===id});var done=bb.filter(function(z){return String(z['Current Stage']).toLowerCase()==='completed';}).length,ret=bb.filter(function(z){return String(z['Retention Status']).toLowerCase()==='retained'||String(z['Current Stage']).toLowerCase()==='retained';}).length;var due=ff.filter(function(z){return z['Next FollowUp']&&new Date(z['Next FollowUp'])<new Date();}).length;var kp=ii.length?ii.reduce(function(a,z){var t=Number(z.Target)||0,c=Number(z['Current Achievement'])||0;return a+(t?Math.min(100,c/t*100):0);},0)/ii.length:0;var qs=q.filter(function(z){return z['Project ID']===id;}).slice(-1)[0];return{'Project ID':id,'Project Name':x['Project Name'],Beneficiaries:bb.length,Completed:done,RetentionRate:bb.length?Math.round(ret/bb.length*100):0,KPIOnTrackRate:Math.round(kp),OverdueFollowUps:due,QualityScore:qs?Number(qs['Overall Score %'])||0:null};});return out;}
function stage9Trends_(projectId){
  var d=stage9Rows_(SHEETS.INDICATORDATA).filter(function(x){return !projectId||x['Project ID']===projectId;});var map={};d.forEach(function(x){var k=x['Indicator ID']+'|'+x.Period;if(!map[k])map[k]={IndicatorID:x['Indicator ID'],Period:x.Period,Achievement:0};map[k].Achievement+=Number(x.Achievement)||0;});return Object.keys(map).map(function(k){return map[k];}).sort(function(a,b){return String(a.Period).localeCompare(String(b.Period));});}
function stage9Forecasts_(projectId){
  var inds=stage9Rows_(SHEETS.INDICATORS).filter(function(x){return projectAllowed_(x['Project ID'])&&(!projectId||x['Project ID']===projectId);}),data=stage9Rows_(SHEETS.INDICATORDATA),out=[];
  inds.forEach(function(i){var hist=data.filter(function(x){return x['Indicator ID']===i['Indicator ID'];}).slice(-6).map(function(x){return Number(x.Achievement)||0;});if(!hist.length)return;var avg=hist.reduce(function(a,b){return a+b;},0)/hist.length,trend=hist.length>1?(hist[hist.length-1]-hist[0])/(hist.length-1):0,proj=Math.max(0,hist[hist.length-1]+trend),target=Number(i.Target)||0,pct=target?proj/target*100:0;out.push({'Indicator ID':i['Indicator ID'],'Project ID':i['Project ID'],Indicator:i.Indicator,CurrentAchievement:hist[hist.length-1],Target:target,ProjectedAchievement:Math.round(proj*100)/100,ProjectedPercent:Math.round(pct*10)/10,ForecastRAG:pct>=100?'Green':pct>=70?'Amber':'Red',Method:'Linear trend (up to 6 observations)'});});return out;}
function stage9Signals_(projectId){
  var p=stage9Portfolio_().filter(function(x){return !projectId||x['Project ID']===projectId;}),signals=[];
  p.forEach(function(x){if(x.RetentionRate<80)signals.push({'Project ID':x['Project ID'],SignalType:'Retention Risk',Severity:x.RetentionRate<60?'Critical':'High',Metric:'Retention rate',CurrentValue:x.RetentionRate,Threshold:80,Message:'Beneficiary retention is below the 80% organizational target.',RecommendedAction:'Review follow-up cases, identify drop-off causes and assign corrective actions.'});if(x.KPIOnTrackRate<70)signals.push({'Project ID':x['Project ID'],SignalType:'KPI Underperformance',Severity:x.KPIOnTrackRate<50?'Critical':'High',Metric:'Average KPI achievement',CurrentValue:x.KPIOnTrackRate,Threshold:70,Message:'Project KPI performance is below the minimum on-track threshold.',RecommendedAction:'Review indicator data, implementation progress, assumptions and resource allocation.'});if(x.OverdueFollowUps>0)signals.push({'Project ID':x['Project ID'],SignalType:'Follow-up Delay',Severity:'Medium',Metric:'Overdue follow-ups',CurrentValue:x.OverdueFollowUps,Threshold:0,Message:'One or more beneficiary follow-ups are overdue.',RecommendedAction:'Assign field officers and complete overdue follow-ups.'});if(x.QualityScore!==null&&x.QualityScore<75)signals.push({'Project ID':x['Project ID'],SignalType:'Data Quality',Severity:x.QualityScore<60?'Critical':'High',Metric:'Overall data quality',CurrentValue:x.QualityScore,Threshold:75,Message:'Data quality is below the organizational minimum.',RecommendedAction:'Resolve data-quality issues before using the dataset for donor reporting or strategic decisions.'});});return signals;}
function stage9Analytics_(projectId){var p=stage9Portfolio_().filter(function(x){return !projectId||x['Project ID']===projectId;}),b=stage9Rows_(SHEETS.BENEFICIARIES).filter(function(x){return projectAllowed_(x['Project ID'])&&(!projectId||x['Project ID']===projectId);}),tr=stage9Trends_(projectId),fc=stage9Forecasts_(projectId),sg=stage9Signals_(projectId);var sex={},county={},community={},age={};b.forEach(function(x){var s=x.Sex||'Unknown',c=x.County||'Unknown',m=x.Community||'Unknown',a=Number(x.Age);sex[s]=(sex[s]||0)+1;county[c]=(county[c]||0)+1;community[m]=(community[m]||0)+1;var band=isNaN(a)?'Unknown':a<10?'Under 10':a<15?'10–14':a<18?'15–17':a<25?'18–24':'25+';age[band]=(age[band]||0)+1;});return{portfolio:p,trends:tr,forecasts:fc,signals:sg,disaggregation:{sex:sex,county:county,community:community,ageBands:age},summary:{projects:p.length,beneficiaries:b.length,signals:sg.length,criticalSignals:sg.filter(function(x){return x.Severity==='Critical';}).length,forecastRed:fc.filter(function(x){return x.ForecastRAG==='Red';}).length}};}
function createStage9Record_(entity,data){var map={forecast:'Forecasts',decisionSignal:'DecisionSignals'},sheet=map[entity];if(!sheet)throw Error('Unsupported Stage 9 entity: '+entity);var p=data['Project ID']||data.ProjectId||'';permission_('create',p);var sh=SpreadsheetApp.getActive().getSheetByName(sheet),h=STAGE9_HEADERS[sheet],o={};h.forEach(function(k){o[k]=data[k]||''});o[h[0]]=id_(entity);o['Created At']=new Date();sh.appendRow(h.map(function(k){return o[k];}));audit_('CREATE',sheet,o[h[0]],o);return json_({ok:true,id:o[h[0]]});}
function stage9GetAction_(a){return ['stage9','advancedAnalytics','portfolioAnalytics','forecastAnalytics','decisionSignals','stage9Setup'].indexOf(a)>=0;}
function stage9Get_(a,e){var pid=e&&e.parameter?e.parameter.projectId||'':'';permission_('read',pid||undefined);if(a==='stage9Setup')return setupStage9();var x=stage9Analytics_(pid);if(a==='portfolioAnalytics')return json_(x.portfolio);if(a==='forecastAnalytics')return json_(x.forecasts);if(a==='decisionSignals')return json_(x.signals);return json_(x);}
function stage9PostAction_(a){return ['stage9Setup','createStage9Record','calculateForecasts','generateDecisionSignals'].indexOf(a)>=0;}
function stage9Post_(a,d){var pid=d.projectId||d['Project ID']||'';if(a==='stage9Setup')return setupStage9();if(a==='createStage9Record')return createStage9Record_(d.entity,d.data||{});permission_('report',pid||undefined);if(a==='calculateForecasts'){var x=stage9Forecasts_(pid);x.forEach(function(r){createStage9Record_('forecast',{'Project ID':r['Project ID'],'Indicator ID':r['Indicator ID'],Period:new Date(),'Current Achievement':r.CurrentAchievement,Target:r.Target,'Projected Achievement':r.ProjectedAchievement,'Projected %':r.ProjectedPercent,'Forecast RAG':r.ForecastRAG,Method:r.Method,'Calculated At':new Date()});});return json_({ok:true,count:x.length,data:x});}if(a==='generateDecisionSignals'){var s=stage9Signals_(pid);s.forEach(function(r){createStage9Record_('decisionSignal',{'Project ID':r['Project ID'],'Signal Type':r.SignalType,Severity:r.Severity,Metric:r.Metric,'Current Value':r.CurrentValue,Threshold:r.Threshold,Message:r.Message,'Recommended Action':r.RecommendedAction,Status:'Open','Created At':new Date()});});return json_({ok:true,count:s.length,data:s});}}
