/* UAF STAGE 14 — COMMUNICATIONS, ADVOCACY, CAMPAIGN & STAKEHOLDER ENGAGEMENT M&E */
var STAGE14_HEADERS={
  Stakeholders:['Stakeholder ID','Name','Organization','Type','County','Community','Contact Person','Email','Phone','Influence','Interest','Relationship Status','Priority','Project Access','Created At','Updated At'],
  Engagements:['Engagement ID','Project ID','Stakeholder ID','Date','Engagement Type','Topic','Objective','Location','Participants','Lead Person','Outcome','Commitments','Next Action','Next Action Due','Status','Evidence URL','Created At'],
  AdvocacyActions:['Advocacy ID','Project ID','Date','Issue','Target Audience','Decision Maker','Advocacy Objective','Action Type','Message','Lead Person','Reach','Outcome','Policy/Practice Change','Status','Evidence URL','Created At'],
  Campaigns:['Campaign ID','Project ID','Campaign Name','Start Date','End Date','Theme','Objective','Target Audience','Target Reach','Actual Reach','Channels','Lead Person','Status','Evidence URL','Created At','Updated At'],
  CampaignActivities:['Campaign Activity ID','Campaign ID','Project ID','Date','Activity','Channel','Community','Target Reach','Actual Reach','Participants','Message','Responsible Person','Outcome','Evidence URL','Status'],
  Communications:['Communication ID','Project ID','Date','Communication Type','Title','Audience','Channel','Key Message','Reach','Engagements','Responsible Person','Publication URL','Evidence URL','Status','Created At'],
  OutreachEvents:['Outreach ID','Project ID','Date','Community','Event Type','Purpose','Target Group','Planned Participants','Actual Participants','Women/Girls','Men/Boys','Children','Lead Person','Outcome','Referral/Action','Evidence URL','Status'],
  Commitments:['Commitment ID','Project ID','Stakeholder ID','Engagement ID','Date','Commitment','Responsible Person','Due Date','Status','Completion Date','Evidence URL','Notes'],
  AdvocacyOutcomes:['Outcome ID','Project ID','Advocacy ID','Date','Outcome Type','Change Observed','Evidence','Contribution','Status','Next Step'],
  CommsAlerts:['Comms Alert ID','Project ID','Stakeholder ID','Campaign ID','Alert Type','Severity','Message','Status','Due Date','Assigned To','Created At']
};
function setupStage14(){var ss=SpreadsheetApp.getActive();Object.keys(STAGE14_HEADERS).forEach(function(n){var s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()==0)s.appendRow(STAGE14_HEADERS[n]);s.setFrozenRows(1);});var s=ss.getSheetByName('Settings');if(s){var old=rows_('Settings');var d={'Stage 14':'Communications, Advocacy, Campaign & Stakeholder Engagement M&E','Engagement Model':'Stakeholder Map → Engage → Commit → Act → Verify Outcome → Learn','Campaign Model':'Plan → Reach → Engage → Measure → Improve','Advocacy Model':'Issue → Objective → Action → Decision Maker → Outcome → Contribution'};Object.keys(d).forEach(function(k){if(!old.some(function(x){return x.Key==k;}))s.appendRow([k,d[k]]);});}return 'Stage 14 setup complete; existing data preserved.';}
function s14n_(v){var n=Number(v);return isNaN(n)?0:n;}
function s14Rows_(name,pid){return rows_(name).filter(function(x){return !pid||String(x['Project ID']||'')===String(pid);});}
function stage14Dashboard_(pid){permission_('read',pid||'');var st=rows_('Stakeholders'),en=s14Rows_('Engagements',pid),av=s14Rows_('AdvocacyActions',pid),ca=s14Rows_('Campaigns',pid),cav=s14Rows_('CampaignActivities',pid),cm=s14Rows_('Communications',pid),oe=s14Rows_('OutreachEvents',pid),co=s14Rows_('Commitments',pid),ao=s14Rows_('AdvocacyOutcomes',pid),al=s14Rows_('CommsAlerts',pid);var activeCampaigns=ca.filter(function(x){return !['completed','closed','inactive'].includes(String(x.Status||'').toLowerCase());});var reach=ca.reduce(function(a,x){return a+s14n_(x['Actual Reach']);},0)+cav.reduce(function(a,x){return a+s14n_(x['Actual Reach']);},0)+cm.reduce(function(a,x){return a+s14n_(x.Reach);},0);var engagementCount=en.length+cm.reduce(function(a,x){return a+s14n_(x.Engagements);},0);var completedCommitments=co.filter(function(x){return ['completed','closed'].indexOf(String(x.Status||'').toLowerCase())>=0;}).length;var dueCommitments=co.filter(function(x){return x['Due Date']&&new Date(x['Due Date'])<new Date()&&!['completed','closed'].includes(String(x.Status||'').toLowerCase());});var advocacyChanges=ao.filter(function(x){return String(x.Status||'').toLowerCase()==='verified'||String(x['Change Observed']||'').trim()!=='';}).length;var participants=oe.reduce(function(a,x){return a+s14n_(x['Actual Participants']);},0);return {summary:{stakeholders:st.length,engagements:en.length,activeCampaigns:activeCampaigns.length,campaigns:ca.length,advocacyActions:av.length,verifiedAdvocacyOutcomes:advocacyChanges,communications:cm.length,outreachEvents:oe.length,outreachParticipants:participants,totalReach:reach,totalEngagements:engagementCount,commitments:co.length,completedCommitments:completedCommitments,overdueCommitments:dueCommitments.length,openAlerts:al.filter(function(x){return String(x.Status||'Open').toLowerCase()!=='resolved';}).length},stakeholders:st,engagements:en,campaigns:ca,advocacy:av,commitments:co,outreach:oe,alerts:al.filter(function(x){return String(x.Status||'Open').toLowerCase()!=='resolved';})};}
function stage14Validate_(entity,d){if(['stakeholder'].indexOf(entity)>=0&&String(d.Name||'').trim()==='')throw Error('Stakeholder name is required.');if(['engagement','advocacyAction','campaign','campaignActivity','communication','outreachEvent'].indexOf(entity)>=0&&!d['Project ID']&&!d.projectId)throw Error('Project ID is required.');if(entity==='campaign'&&s14n_(d['Target Reach'])<0)throw Error('Target reach cannot be negative.');if(entity==='campaignActivity'&&(s14n_(d['Target Reach'])<0||s14n_(d['Actual Reach'])<0))throw Error('Reach cannot be negative.');if(entity==='outreachEvent'&&s14n_(d['Actual Participants'])<0)throw Error('Participants cannot be negative.');}
function createStage14Record_(entity,data){var map={stakeholder:'Stakeholders',engagement:'Engagements',advocacyAction:'AdvocacyActions',campaign:'Campaigns',campaignActivity:'CampaignActivities',communication:'Communications',outreachEvent:'OutreachEvents',commitment:'Commitments',advocacyOutcome:'AdvocacyOutcomes',commsAlert:'CommsAlerts'},sheet=map[entity];if(!sheet)throw Error('Unsupported Stage 14 entity');var pid=data['Project ID']||data.projectId||'';permission_('create',pid);stage14Validate_(entity,data);var s=SpreadsheetApp.getActive().getSheetByName(sheet),h=STAGE14_HEADERS[sheet],now=new Date(),prefix=entity==='stakeholder'?'STK':entity==='engagement'?'ENG':entity==='advocacyAction'?'ADV':entity==='campaign'?'CMP':entity==='campaignActivity'?'CAM':entity==='communication'?'COM':entity==='outreachEvent'?'OUT':entity==='commitment'?'CMT':entity==='advocacyOutcome'?'AOV':'CAL',id=id_(prefix);s.appendRow(h.map(function(k){if(k==='Created At'||k==='Updated At')return now;if(/ID$/.test(k)&&!data[k])return id;return data[k]!==undefined?data[k]:'';}));audit_('CREATE',entity,id,data);return json_({ok:true,id:id});}
function stage14GenerateAlerts_(pid){permission_('update',pid||'');var s=SpreadsheetApp.getActive().getSheetByName('CommsAlerts'),created=0,today=new Date(),co=s14Rows_('Commitments',pid),ca=s14Rows_('Campaigns',pid),en=s14Rows_('Engagements',pid);co.forEach(function(x){if(x['Due Date']&&new Date(x['Due Date'])<today&&!['completed','closed'].includes(String(x.Status||'').toLowerCase())){s.appendRow([id_('CAL'),pid,x['Stakeholder ID'],'','COMMITMENT_OVERDUE','High','Stakeholder commitment is overdue: '+x.Commitment,'Open',x['Due Date'],x['Responsible Person'],today]);created++;}});ca.forEach(function(x){if(x['End Date']&&new Date(x['End Date'])<today&&!['completed','closed'].includes(String(x.Status||'').toLowerCase())){s.appendRow([id_('CAL'),pid,'',x['Campaign ID'],'CAMPAIGN_OVERDUE','Amber','Campaign has passed its end date but is not closed.','Open',x['End Date'],x['Lead Person'],today]);created++;}});en.forEach(function(x){if(x['Next Action Due']&&new Date(x['Next Action Due'])<today&&!['completed','closed'].includes(String(x.Status||'').toLowerCase())){s.appendRow([id_('CAL'),pid,x['Stakeholder ID'],'','ENGAGEMENT_ACTION_DUE','Amber','Engagement follow-up action is overdue.','Open',x['Next Action Due'],x['Lead Person'],today]);created++;}});return json_({ok:true,created:created});}
function stage14GetAction_(a){return ['stage14','communicationsDashboard','stakeholders','engagements','advocacyActions','campaigns','campaignActivities','communications','outreachEvents','commitments','advocacyOutcomes','commsAlerts'].indexOf(a)>=0;}
function stage14Get_(a,e){var pid=e&&e.parameter?e.parameter.projectId||'':'';if(a==='stage14'||a==='communicationsDashboard')return json_({ok:true,data:stage14Dashboard_(pid)});var map={stakeholders:'Stakeholders',engagements:'Engagements',advocacyActions:'AdvocacyActions',campaigns:'Campaigns',campaignActivities:'CampaignActivities',communications:'Communications',outreachEvents:'OutreachEvents',commitments:'Commitments',advocacyOutcomes:'AdvocacyOutcomes',commsAlerts:'CommsAlerts'},n=map[a];permission_('read',pid);return json_({ok:true,data:s14Rows_(n,pid)});}
function stage14PostAction_(a){return ['stage14Setup','createStage14Record','generateCommsAlerts'].indexOf(a)>=0;}
function stage14Post_(a,d){if(a==='stage14Setup'){permission_('update');return json_({ok:true,message:setupStage14()});}if(a==='createStage14Record')return createStage14Record_(d.entity,d.data||{});if(a==='generateCommsAlerts')return stage14GenerateAlerts_(d.projectId||'');}
