/* UAF STAGE 13 — HR, STAFF, VOLUNTEER & WORKPLAN MANAGEMENT M&E */
var STAGE13_HEADERS={
  Staff:['Staff ID','Name','Email','Phone','Role','Department/Unit','Employment Type','Start Date','End Date','County','Status','Supervisor','Skills','Project Access','Created At','Updated At'],
  Volunteers:['Volunteer ID','Name','Email','Phone','Role','Community','Start Date','End Date','Status','Supervisor','Skills','Project Access','Created At'],
  Assignments:['Assignment ID','Project ID','Staff/Volunteer ID','Person Type','Activity ID','Role','Start Date','End Date','Allocation %','Status'],
  Attendance:['Attendance ID','Person ID','Person Type','Date','Check In','Check Out','Status','Location','Project ID','Activity ID','Notes'],
  Timesheets:['Timesheet ID','Person ID','Person Type','Project ID','Activity ID','Date','Hours','Work Description','Status','Approved By','Approved Date'],
  Training:['Training ID','Person ID','Person Type','Project ID','Training Title','Date','Provider','Hours','Cost','Skills/Competency','Outcome','Evidence URL'],
  Performance:['Performance ID','Person ID','Person Type','Review Period','Objectives','Achievement','Strengths','Development Needs','Rating','Reviewer','Review Date'],
  Leave:['Leave ID','Person ID','Person Type','Leave Type','Start Date','End Date','Days','Reason','Status','Approved By'],
  Workplans:['Workplan ID','Person ID','Person Type','Project ID','Period Start','Period End','Objective/Activity','Planned Output','Target','Actual','Status','Notes'],
  FieldDeployments:['Deployment ID','Person ID','Person Type','Project ID','Community','Date','Activity','Purpose','Start Time','End Time','Transport/Per Diem Cost','Evidence URL','Status'],
  HRAlerts:['HR Alert ID','Person ID','Person Type','Project ID','Alert Type','Severity','Message','Status','Due Date','Assigned To','Created At']
};
function setupStage13(){var ss=SpreadsheetApp.getActive();Object.keys(STAGE13_HEADERS).forEach(function(n){var s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()==0)s.appendRow(STAGE13_HEADERS[n]);s.setFrozenRows(1);});var s=ss.getSheetByName('Settings');if(s){var old=rows_('Settings');var d={'Stage 13':'HR, Staff, Volunteer & Workplan Management M&E','Personnel Model':'Staff + Volunteers → Assignments → Attendance → Timesheets → Performance','Workplan Model':'Plan → Assign → Execute → Record → Review → Learn','Field Deployment Model':'Deployment → Activity → Evidence → Cost → Review'};Object.keys(d).forEach(function(k){if(!old.some(function(x){return x.Key==k;}))s.appendRow([k,d[k]]);});}return 'Stage 13 setup complete; existing data preserved.';}
function s13n_(v){var n=Number(v);return isNaN(n)?0:n;}
function s13Rows_(name,pid){var a=rows_(name);return a.filter(function(x){return !pid||String(x['Project ID']||'')===String(pid);});}
function stage13Dashboard_(pid){permission_('read',pid||'');var staff=rows_('Staff').filter(function(x){return String(x.Status||'').toLowerCase()!=='inactive';}),vol=rows_('Volunteers').filter(function(x){return String(x.Status||'').toLowerCase()!=='inactive';}),as=s13Rows_('Assignments',pid),att=s13Rows_('Attendance',pid),ts=s13Rows_('Timesheets',pid),tr=s13Rows_('Training',pid),pf=rows_('Performance'),lv=rows_('Leave'),wp=s13Rows_('Workplans',pid),fd=s13Rows_('FieldDeployments',pid),al=s13Rows_('HRAlerts',pid);var activeAssignments=as.filter(function(x){return String(x.Status||'Active').toLowerCase()==='active';});var allocation={};activeAssignments.forEach(function(x){var id=String(x['Staff/Volunteer ID']);allocation[id]=(allocation[id]||0)+s13n_(x['Allocation %']);});var overallocated=Object.keys(allocation).filter(function(k){return allocation[k]>100;}).length;var present=att.filter(function(x){return ['present','late','field'].indexOf(String(x.Status||'').toLowerCase())>=0;}).length;var attendanceRate=att.length?Math.round(present/att.length*10000)/100:0;var approvedHours=ts.filter(function(x){return String(x.Status||'').toLowerCase()==='approved';}).reduce(function(a,x){return a+s13n_(x.Hours);},0);var completedWp=wp.filter(function(x){return String(x.Status||'').toLowerCase()==='completed';}).length;var wpRate=wp.length?Math.round(completedWp/wp.length*10000)/100:0;var openAlerts=al.filter(function(x){return String(x.Status||'Open').toLowerCase()!=='resolved';});var expiring=staff.filter(function(x){return x['End Date']&&((new Date(x['End Date'])-new Date())/86400000)<=30&&((new Date(x['End Date'])-new Date())/86400000)>=0;}).length;return {summary:{activeStaff:staff.length,activeVolunteers:vol.length,assignments:as.length,activeAssignments:activeAssignments.length,overallocatedPeople:overallocated,attendanceRate:attendanceRate,timesheetHours:approvedHours,trainingRecords:tr.length,performanceReviews:pf.length,leaveRecords:lv.length,workplans:wp.length,workplanCompletionRate:wpRate,fieldDeployments:fd.length,openAlerts:openAlerts.length,contractsExpiring30Days:expiring},allocation:Object.keys(allocation).map(function(k){return {personId:k,allocation:allocation[k],status:allocation[k]>100?'Overallocated':allocation[k]>=80?'High':'Normal'};}),workplans:wp,deployments:fd,alerts:openAlerts};}
function stage13Validate_(entity,d){if(['Staff','Volunteers'].indexOf(entity)>=0&&String(d.Name||'').trim()==='')throw Error('Name is required.');if(entity==='Assignments'&&!d['Project ID'])throw Error('Project ID is required for assignments.');if(entity==='Timesheets'){if(!d['Project ID'])throw Error('Project ID is required for timesheets.');if(s13n_(d.Hours)<0)throw Error('Hours cannot be negative.');}if(entity==='Training'&&s13n_(d.Hours)<0)throw Error('Training hours cannot be negative.');if(entity==='FieldDeployments'&&s13n_(d['Transport/Per Diem Cost'])<0)throw Error('Deployment cost cannot be negative.');if(entity==='Workplans'&&s13n_(d.Target)<0)throw Error('Workplan target cannot be negative.');}
function createStage13Record_(entity,data){var map={staff:'Staff',volunteer:'Volunteers',assignment:'Assignments',attendance:'Attendance',timesheet:'Timesheets',training:'Training',performance:'Performance',leave:'Leave',workplan:'Workplans',fieldDeployment:'FieldDeployments',hrAlert:'HRAlerts'},sheet=map[entity];if(!sheet)throw Error('Unsupported Stage 13 entity');var pid=data['Project ID']||data.projectId||'';permission_('create',pid);stage13Validate_(sheet,data);var s=SpreadsheetApp.getActive().getSheetByName(sheet),h=STAGE13_HEADERS[sheet],now=new Date(),prefix=entity==='staff'?'STF':entity==='volunteer'?'VOL':entity==='assignment'?'ASN':entity==='attendance'?'ATT':entity==='timesheet'?'TMS':entity==='training'?'TRN':entity==='performance'?'PRF':entity==='leave'?'LEV':entity==='workplan'?'WPL':entity==='fieldDeployment'?'DEP':'HRA',id=id_(prefix);s.appendRow(h.map(function(k){if(k==='Created At'||k==='Updated At')return now;if(/ID$/.test(k)&&!data[k])return id;return data[k]!==undefined?data[k]:'';}));audit_('CREATE',entity,id,data);return json_({ok:true,id:id});}
function stage13GenerateAlerts_(pid){permission_('update',pid||'');var created=0,s=SpreadsheetApp.getActive().getSheetByName('HRAlerts'),today=new Date(),staff=rows_('Staff'),as=s13Rows_('Assignments',pid),ts=s13Rows_('Timesheets',pid),wp=s13Rows_('Workplans',pid);staff.forEach(function(x){if(x['End Date']){var days=Math.ceil((new Date(x['End Date'])-today)/86400000);if(days>=0&&days<=30){s.appendRow([id_('HRA'),x['Staff ID'],'Staff',pid,'CONTRACT_EXPIRY','Amber','Staff contract/engagement ends in '+days+' day(s).','Open',x['End Date'],x.Supervisor,today]);created++;}}});var alloc={};as.filter(function(x){return String(x.Status||'Active').toLowerCase()==='active';}).forEach(function(x){var id=String(x['Staff/Volunteer ID']);alloc[id]=(alloc[id]||0)+s13n_(x['Allocation %']);});Object.keys(alloc).forEach(function(id){if(alloc[id]>100){s.appendRow([id_('HRA'),id,'',pid,'OVERALLOCATION','High','Personnel allocation exceeds 100% ('+alloc[id]+'%).','Open','', '',today]);created++;}});var cutoff=new Date(today.getTime()-14*86400000);ts.forEach(function(x){var dt=new Date(x.Date);if(String(x.Status||'').toLowerCase()!=='approved'&&dt<cutoff){s.appendRow([id_('HRA'),x['Person ID'],x['Person Type'],x['Project ID'],'TIMESHEET_OVERDUE','Amber','Timesheet is more than 14 days old and remains unapproved.','Open','',x['Approved By']||'',today]);created++;}});wp.forEach(function(x){if(String(x.Status||'').toLowerCase()==='overdue'){s.appendRow([id_('HRA'),x['Person ID'],x['Person Type'],x['Project ID'],'WORKPLAN_OVERDUE','Amber','Workplan item is marked overdue.','Open','', '',today]);created++;}});return json_({ok:true,created:created});}
function stage13GetAction_(a){return ['stage13','hrDashboard','staff','volunteers','assignments','attendance','timesheets','training','performance','leave','workplans','fieldDeployments','hrAlerts'].indexOf(a)>=0;}
function stage13Get_(a,e){var pid=e&&e.parameter?e.parameter.projectId||'':'';if(a==='stage13'||a==='hrDashboard')return json_({ok:true,data:stage13Dashboard_(pid)});var map={staff:'Staff',volunteers:'Volunteers',assignments:'Assignments',attendance:'Attendance',timesheets:'Timesheets',training:'Training',performance:'Performance',leave:'Leave',workplans:'Workplans',fieldDeployments:'FieldDeployments',hrAlerts:'HRAlerts'},n=map[a];permission_('read',pid);return json_({ok:true,data:s13Rows_(n,pid)});}
function stage13PostAction_(a){return ['stage13Setup','createStage13Record','generateHRAlerts'].indexOf(a)>=0;}
function stage13Post_(a,d){if(a==='stage13Setup'){permission_('update');return json_({ok:true,message:setupStage13()});}if(a==='createStage13Record')return createStage13Record_(d.entity,d.data||{});if(a==='generateHRAlerts')return stage13GenerateAlerts_(d.projectId||'');}
