/* UAF STAGE 17 — SUSTAINABILITY, EXIT STRATEGY & ORGANIZATIONAL RESILIENCE M&E */
var STAGE17_HEADERS={
 SustainabilityPlans:['Plan ID','Project ID','Sustainability Area','Objective','Strategy','Owner','Start Date','Review Date','Target','Actual','Status','Evidence URL','Created At','Updated At'],
 ExitPlans:['Exit Plan ID','Project ID','Exit Strategy','Exit Criteria','Responsible Person','Start Date','Exit Date','Status','Readiness %','Evidence URL','Created At','Updated At'],
 SustainabilityIndicators:['Indicator ID','Project ID','Sustainability Area','Indicator','Definition','Baseline','Target','Current Achievement','Unit','Frequency','Data Source','Responsible Person','Status','Last Updated'],
 LocalOwnership:['Ownership ID','Project ID','Community','Stakeholder','Role','Capacity Level','Contribution','Decision Making Level','Ownership Score','Evidence URL','Status','Review Date','Created At'],
 CapacityTransfer:['Transfer ID','Project ID','Recipient','Organization/Group','Capacity Area','Baseline Capacity','Target Capacity','Current Capacity','Training/Coaching','Date','Evidence URL','Status','Follow-up Date','Created At'],
 ResourceMobilization:['Mobilization ID','Project ID','Date','Source','Funding Type','Amount','Currency','Purpose','Status','Evidence URL','Responsible Person','Created At'],
 SustainabilityFunding:['Funding ID','Project ID','Funding Source','Funding Type','Amount','Currency','Start Date','End Date','Status','Probability','Notes','Created At'],
 ResilienceRisks:['Risk ID','Project ID','Date','Risk Category','Risk','Likelihood','Impact','Score','Mitigation','Contingency Plan','Owner','Review Date','Status','Created At'],
 ResilienceAssessments:['Assessment ID','Project ID','Date','Area','Score','Maximum Score','Percentage','Evidence','Gap','Action Required','Reviewer','Status'],
 ContinuityPlans:['Continuity ID','Project ID','Risk/Event','Critical Function','Response Action','Responsible Person','Backup Person','Resources Required','Communication Plan','Recovery Target','Status','Last Tested','Evidence URL','Created At'],
 SustainabilityCommitments:['Commitment ID','Project ID','Stakeholder','Commitment','Due Date','Status','Completion Date','Evidence URL','Owner','Notes','Created At'],
 SustainabilityAlerts:['Alert ID','Project ID','Alert Type','Severity','Message','Status','Due Date','Assigned To','Created At']
};
function setupStage17(){var ss=SpreadsheetApp.getActive();Object.keys(STAGE17_HEADERS).forEach(function(n){var s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()==0)s.appendRow(STAGE17_HEADERS[n]);s.setFrozenRows(1);});var s=ss.getSheetByName('Settings');if(s){var d={'Stage 17':'Sustainability, Exit Strategy & Organizational Resilience M&E','Sustainability Model':'Ownership → Capacity → Resources → Systems → Continuity → Exit','Exit Model':'Prepare → Transfer → Test → Exit → Follow-up → Sustain'};var old=rows_('Settings');Object.keys(d).forEach(function(k){if(!old.some(function(x){return x.Key==k;}))s.appendRow([k,d[k]]);});}return 'Stage 17 setup complete; existing data preserved.';}
function s17Rows_(n,pid){return rows_(n).filter(function(x){return !pid||String(x['Project ID']||'')===String(pid);});}
function s17n_(v){var n=Number(v);return isNaN(n)?0:n;}
function stage17Dashboard_(pid){permission_('read',pid||'');var sp=s17Rows_('SustainabilityPlans',pid),ep=s17Rows_('ExitPlans',pid),si=s17Rows_('SustainabilityIndicators',pid),lo=s17Rows_('LocalOwnership',pid),ct=s17Rows_('CapacityTransfer',pid),rm=s17Rows_('ResourceMobilization',pid),sf=s17Rows_('SustainabilityFunding',pid),rr=s17Rows_('ResilienceRisks',pid),ra=s17Rows_('ResilienceAssessments',pid),cp=s17Rows_('ContinuityPlans',pid),sc=s17Rows_('SustainabilityCommitments',pid),al=s17Rows_('SustainabilityAlerts',pid);var activePlans=sp.filter(function(x){return !['completed','closed','inactive'].includes(String(x.Status||'').toLowerCase());}).length;var exitReady=ep.length?Math.round(ep.reduce(function(a,x){return a+s17n_(x['Readiness %']);},0)/ep.length*100)/100:0;var ownership=lo.length?Math.round(lo.reduce(function(a,x){return a+s17n_(x['Ownership Score']);},0)/lo.length*100)/100:0;var capacity=ct.length?Math.round(ct.reduce(function(a,x){return a+(s17n_(x['Current Capacity'])/(s17n_(x['Target Capacity'])||1))*100;},0)/ct.length*100)/100:0;var resilience=ra.length?Math.round(ra.reduce(function(a,x){return a+(s17n_(x.Percentage)||((s17n_(x.Score)/(s17n_(x['Maximum Score'])||1))*100));},0)/ra.length*100)/100:0;var openRisks=rr.filter(function(x){return !['closed','resolved'].includes(String(x.Status||'').toLowerCase());}).length;var overdue=sc.filter(function(x){return x['Due Date']&&new Date(x['Due Date'])<new Date()&&!['completed','closed'].includes(String(x.Status||'').toLowerCase());}).length;var openAlerts=al.filter(function(x){return String(x.Status||'Open').toLowerCase()!=='resolved';}).length;return {summary:{sustainabilityPlans:sp.length,activePlans:activePlans,exitPlans:ep.length,exitReadiness:exitReady,indicators:si.length,localOwnershipRecords:lo.length,ownershipScore:ownership,capacityTransfers:ct.length,capacityScore:capacity,resourcesMobilized:rm.length,fundingRecords:sf.length,resilienceRisks:rr.length,openRisks:openRisks,resilienceScore:resilience,continuityPlans:cp.length,commitments:sc.length,overdueCommitments:overdue,openAlerts:openAlerts},sustainabilityPlans:sp,exitPlans:ep,indicators:si,ownership:lo,capacityTransfers:ct,resourceMobilization:rm,funding:sf,risks:rr,assessments:ra,continuity:cp,commitments:sc,alerts:al.filter(function(x){return String(x.Status||'Open').toLowerCase()!=='resolved';})};}
function stage17Validate_(entity,d){var needsProject=['sustainabilityPlan','exitPlan','sustainabilityIndicator','localOwnership','capacityTransfer','resourceMobilization','sustainabilityFunding','resilienceRisk','resilienceAssessment','continuityPlan','sustainabilityCommitment'];if(needsProject.indexOf(entity)>=0&&!d['Project ID']&&!d.projectId)throw Error('Project ID is required.');if(entity==='sustainabilityPlan'&&!String(d.Strategy||'').trim())throw Error('Sustainability strategy is required.');if(entity==='exitPlan'&&!String(d['Exit Strategy']||'').trim())throw Error('Exit strategy is required.');}
function createStage17Record_(entity,data){var map={sustainabilityPlan:'SustainabilityPlans',exitPlan:'ExitPlans',sustainabilityIndicator:'SustainabilityIndicators',localOwnership:'LocalOwnership',capacityTransfer:'CapacityTransfer',resourceMobilization:'ResourceMobilization',sustainabilityFunding:'SustainabilityFunding',resilienceRisk:'ResilienceRisks',resilienceAssessment:'ResilienceAssessments',continuityPlan:'ContinuityPlans',sustainabilityCommitment:'SustainabilityCommitments',sustainabilityAlert:'SustainabilityAlerts'},sheet=map[entity];if(!sheet)throw Error('Unsupported Stage 17 entity');var pid=data['Project ID']||data.projectId||'';permission_('create',pid);stage17Validate_(entity,data);var s=SpreadsheetApp.getActive().getSheetByName(sheet),h=STAGE17_HEADERS[sheet],prefix={sustainabilityPlan:'SUS',exitPlan:'EXT',sustainabilityIndicator:'SIN',localOwnership:'OWN',capacityTransfer:'CAP',resourceMobilization:'RMB',sustainabilityFunding:'FUN',resilienceRisk:'RSK',resilienceAssessment:'RSA',continuityPlan:'CON',sustainabilityCommitment:'COM',sustainabilityAlert:'SAL'}[entity],id=id_(prefix),now=new Date();s.appendRow(h.map(function(k){if(k==='Created At'||k==='Updated At')return now;if(/ID$/.test(k)&&!data[k])return id;return data[k]!==undefined?data[k]:'';}));audit_('CREATE',entity,id,data);return json_({ok:true,id:id});}
function stage17GenerateAlerts_(pid){permission_('update',pid||'');var s=SpreadsheetApp.getActive().getSheetByName('SustainabilityAlerts'),created=0,today=new Date();s17Rows_('ExitPlans',pid).forEach(function(x){if(x['Exit Date']&&new Date(x['Exit Date'])<today&&!['completed','closed'].includes(String(x.Status||'').toLowerCase())){s.appendRow([id_('SAL'),pid,'EXIT_OVERDUE','High','Exit plan date has passed without completion.','Open',x['Exit Date'],x['Responsible Person'],today]);created++;}});s17Rows_('SustainabilityCommitments',pid).forEach(function(x){if(x['Due Date']&&new Date(x['Due Date'])<today&&!['completed','closed'].includes(String(x.Status||'').toLowerCase())){s.appendRow([id_('SAL'),pid,'COMMITMENT_OVERDUE','Amber','Sustainability commitment is overdue.','Open',x['Due Date'],x.Owner,today]);created++;}});s17Rows_('ResilienceRisks',pid).forEach(function(x){if(s17n_(x.Score)>=12&&!['closed','resolved'].includes(String(x.Status||'').toLowerCase())){s.appendRow([id_('SAL'),pid,'HIGH_RESILIENCE_RISK','High','High resilience risk requires management action.','Open',x['Review Date'],x.Owner,today]);created++;}});return json_({ok:true,created:created});}
function stage17GetAction_(a){return ['stage17','sustainabilityDashboard','sustainabilityPlans','exitPlans','sustainabilityIndicators','localOwnership','capacityTransfer','resourceMobilization','sustainabilityFunding','resilienceRisks','resilienceAssessments','continuityPlans','sustainabilityCommitments','sustainabilityAlerts'].indexOf(a)>=0;}
function stage17Get_(a,e){var pid=e&&e.parameter?e.parameter.projectId||'':'';if(a==='stage17'||a==='sustainabilityDashboard')return json_({ok:true,data:stage17Dashboard_(pid)});var map={sustainabilityPlans:'SustainabilityPlans',exitPlans:'ExitPlans',sustainabilityIndicators:'SustainabilityIndicators',localOwnership:'LocalOwnership',capacityTransfer:'CapacityTransfer',resourceMobilization:'ResourceMobilization',sustainabilityFunding:'SustainabilityFunding',resilienceRisks:'ResilienceRisks',resilienceAssessments:'ResilienceAssessments',continuityPlans:'ContinuityPlans',sustainabilityCommitments:'SustainabilityCommitments',sustainabilityAlerts:'SustainabilityAlerts'},n=map[a];permission_('read',pid);return json_({ok:true,data:s17Rows_(n,pid)});}
function stage17PostAction_(a){return ['stage17Setup','createStage17Record','generateSustainabilityAlerts'].indexOf(a)>=0;}
function stage17Post_(a,d){if(a==='stage17Setup'){permission_('update');return json_({ok:true,message:setupStage17()});}if(a==='createStage17Record')return createStage17Record_(d.entity,d.data||{});if(a==='generateSustainabilityAlerts')return stage17GenerateAlerts_(d.projectId||'');}
