/* UAF STAGE 18 — SAFEGUARDING, CHILD PROTECTION, PSEA & DO-NO-HARM M&E */
var STAGE18_HEADERS={
 SafeguardingPolicies:['Policy ID','Policy Type','Title','Version','Effective Date','Review Date','Owner','Status','Document URL','Created At'],
 SafeguardingTraining:['Training ID','Project ID','Training Type','Date','Participants','Facilitator','Topics','Completion Status','Evidence URL','Created At'],
 SafeguardingRisks:['Risk ID','Project ID','Date','Risk Category','Risk','Affected Group','Likelihood','Impact','Score','Mitigation','Owner','Review Date','Status','Created At'],
 ProtectionCases:['Case ID','Project ID','Date Reported','Incident Category','Safeguarding Concern','Risk Level','Immediate Safety Action','Referral Required','Referral Status','Assigned Officer','Case Status','Closure Date','Evidence URL','Created At','Updated At'],
 Referrals:['Referral ID','Case ID','Project ID','Date','Service Type','Provider','Location','Referral Reason','Consent Status','Referral Status','Follow-up Date','Outcome','Created At'],
 PSEAReports:['PSEA Report ID','Project ID','Date Reported','Report Type','Allegation/Concern','Risk Level','Reporting Channel','Confidentiality Level','Immediate Action','Referral Required','Status','Assigned Officer','Closure Date','Created At'],
 FeedbackComplaints:['Feedback ID','Project ID','Date','Channel','Category','Feedback/Complaint','Anonymous','Risk Level','Action Required','Assigned To','Status','Response Date','Evidence URL','Created At'],
 ChildConsent:['Consent ID','Project ID','Beneficiary ID','Date','Consent Type','Consent Given','Guardian/Responsible Adult','Assent Required','Assent Given','Data Use Permission','Photo/Media Permission','Consent Review Date','Recorded By','Created At'],
 SafeProgramming:['Check ID','Project ID','Activity ID','Date','Safeguarding Check','Standard','Result','Risk/Issue','Corrective Action','Responsible Person','Due Date','Status','Verified By','Evidence URL','Created At'],
 SafeguardingIncidents:['Incident ID','Project ID','Date','Incident Type','Location','Persons Affected','Severity','Action Taken','Referral Made','Status','Responsible Person','Follow-up Date','Evidence URL','Created At'],
 AccountabilityActions:['Action ID','Project ID','Date','Source','Issue','Action','Owner','Due Date','Status','Completion Date','Evidence URL','Created At'],
 SafeguardingAlerts:['Alert ID','Project ID','Alert Type','Severity','Message','Status','Due Date','Assigned To','Created At']
};
function setupStage18(){var ss=SpreadsheetApp.getActive();Object.keys(STAGE18_HEADERS).forEach(function(n){var s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()==0)s.appendRow(STAGE18_HEADERS[n]);s.setFrozenRows(1);});var s=ss.getSheetByName('Settings');if(s){var d={'Stage 18':'Safeguarding, Child Protection, PSEA & Do-No-Harm M&E','Safeguarding Principle':'Best interests of the child; confidentiality; informed consent; survivor-centred response; do no harm','Accountability Channels':'Feedback, complaints, safeguarding reporting, PSEA reporting and referrals'};var old=rows_('Settings');Object.keys(d).forEach(function(k){if(!old.some(function(x){return x.Key==k;}))s.appendRow([k,d[k]]);});}return 'Stage 18 setup complete; existing data preserved.';}
function s18Rows_(n,pid){return rows_(n).filter(function(x){return !pid||String(x['Project ID']||'')===String(pid);});}
function s18n_(v){var n=Number(v);return isNaN(n)?0:n;}
function stage18Dashboard_(pid){permission_('read',pid||'');var pol=rows_('SafeguardingPolicies'),tr=s18Rows_('SafeguardingTraining',pid),rk=s18Rows_('SafeguardingRisks',pid),pc=s18Rows_('ProtectionCases',pid),rf=s18Rows_('Referrals',pid),ps=s18Rows_('PSEAReports',pid),fc=s18Rows_('FeedbackComplaints',pid),cc=s18Rows_('ChildConsent',pid),sp=s18Rows_('SafeProgramming',pid),si=s18Rows_('SafeguardingIncidents',pid),aa=s18Rows_('AccountabilityActions',pid),al=s18Rows_('SafeguardingAlerts',pid);var openCases=pc.filter(function(x){return !['closed','resolved'].includes(String(x['Case Status']||'').toLowerCase());}).length;var highRisks=rk.filter(function(x){return s18n_(x.Score)>=12&&!['closed','resolved'].includes(String(x.Status||'').toLowerCase());}).length;var referralsOpen=rf.filter(function(x){return !['completed','closed'].includes(String(x['Referral Status']||'').toLowerCase());}).length;var pseaOpen=ps.filter(function(x){return !['closed','resolved'].includes(String(x.Status||'').toLowerCase());}).length;var complaintsOpen=fc.filter(function(x){return !['closed','resolved'].includes(String(x.Status||'').toLowerCase());}).length;var checks=s18n_(sp.length),passes=sp.filter(function(x){return ['pass','compliant','yes'].indexOf(String(x.Result||'').toLowerCase())>=0;}).length;var compliance=checks?Math.round(passes/checks*10000)/100:0;var alertsOpen=al.filter(function(x){return !['resolved','closed'].includes(String(x.Status||'').toLowerCase());}).length;return {summary:{policies:pol.length,trainings:tr.length,safeguardingRisks:rk.length,highRisks:highRisks,protectionCases:pc.length,openCases:openCases,referrals:rf.length,openReferrals:referralsOpen,pseaReports:ps.length,openPSEA:pseaOpen,feedbackComplaints:fc.length,openComplaints:complaintsOpen,consentRecords:cc.length,safeProgrammingChecks:checks,safeguardingCompliance:compliance,incidents:si.length,accountabilityActions:aa.length,openAlerts:alertsOpen},policies:pol,training:tr,risks:rk,cases:pc,referrals:rf,psea:ps,feedback:fc,consent:cc,safeProgramming:sp,incidents:si,accountability:aa,alerts:al.filter(function(x){return !['resolved','closed'].includes(String(x.Status||'').toLowerCase());})};}
function stage18Validate_(entity,d){var req=['safeguardingRisk','protectionCase','referral','pseaReport','feedbackComplaint','childConsent','safeProgramming','safeguardingIncident','accountabilityAction'];if(req.indexOf(entity)>=0&&!d['Project ID']&&!d.projectId)throw Error('Project ID is required.');if(entity==='protectionCase'&&!String(d['Safeguarding Concern']||'').trim())throw Error('Safeguarding concern is required.');if(entity==='pseaReport'&&!String(d['Allegation/Concern']||'').trim())throw Error('PSEA allegation/concern is required.');}
function createStage18Record_(entity,data){var map={safeguardingPolicy:'SafeguardingPolicies',safeguardingTraining:'SafeguardingTraining',safeguardingRisk:'SafeguardingRisks',protectionCase:'ProtectionCases',referral:'Referrals',pseaReport:'PSEAReports',feedbackComplaint:'FeedbackComplaints',childConsent:'ChildConsent',safeProgramming:'SafeProgramming',safeguardingIncident:'SafeguardingIncidents',accountabilityAction:'AccountabilityActions',safeguardingAlert:'SafeguardingAlerts'},sheet=map[entity];if(!sheet)throw Error('Unsupported Stage 18 entity');var pid=data['Project ID']||data.projectId||'';permission_('create',pid);stage18Validate_(entity,data);var s=SpreadsheetApp.getActive().getSheetByName(sheet),h=STAGE18_HEADERS[sheet],prefix={safeguardingPolicy:'POL',safeguardingTraining:'SFT',safeguardingRisk:'SRK',protectionCase:'CAS',referral:'REF',pseaReport:'PSE',feedbackComplaint:'FDB',childConsent:'CNS',safeProgramming:'SPC',safeguardingIncident:'INC',accountabilityAction:'ACC',safeguardingAlert:'SAL'}[entity],id=id_(prefix),now=new Date();s.appendRow(h.map(function(k){if(k==='Created At'||k==='Updated At')return now;if(/ID$/.test(k)&&!data[k])return id;return data[k]!==undefined?data[k]:'';}));audit_('CREATE',entity,id,data);return json_({ok:true,id:id});}
function stage18GenerateAlerts_(pid){permission_('update',pid||'');var s=SpreadsheetApp.getActive().getSheetByName('SafeguardingAlerts'),now=new Date(),created=0;function add(type,severity,msg,due,owner){s.appendRow([id_('SAL'),pid,type,severity,msg,'Open',due||'',owner||'',now]);created++;}s18Rows_('ProtectionCases',pid).forEach(function(x){if(['high','critical'].indexOf(String(x['Risk Level']||'').toLowerCase())>=0&&!['closed','resolved'].includes(String(x['Case Status']||'').toLowerCase()))add('HIGH_PROTECTION_CASE','Critical','High/critical safeguarding case requires immediate management attention.',x['Closure Date'],x['Assigned Officer']);if(x['Referral Required']&&String(x['Referral Required']).toLowerCase()==='yes'&&!['completed','closed'].includes(String(x['Referral Status']||'').toLowerCase()))add('REFERRAL_PENDING','High','Safeguarding referral remains open.',x['Closure Date'],x['Assigned Officer']);});s18Rows_('PSEAReports',pid).forEach(function(x){if(!['closed','resolved'].includes(String(x.Status||'').toLowerCase()))add('PSEA_CASE_OPEN','Critical','PSEA report requires confidential follow-up.',x['Closure Date'],x['Assigned Officer']);});s18Rows_('SafeguardingRisks',pid).forEach(function(x){if(s18n_(x.Score)>=12&&!['closed','resolved'].includes(String(x.Status||'').toLowerCase()))add('SAFEGUARDING_RISK','High','High safeguarding risk requires mitigation and review.',x['Review Date'],x.Owner);});return json_({ok:true,created:created});}
function stage18GetAction_(a){return ['stage18','safeguardingDashboard','safeguardingPolicies','safeguardingTraining','safeguardingRisks','protectionCases','referrals','pseaReports','feedbackComplaints','childConsent','safeProgramming','safeguardingIncidents','accountabilityActions','safeguardingAlerts'].indexOf(a)>=0;}
function stage18Get_(a,e){var pid=e&&e.parameter?e.parameter.projectId||'':'';if(a==='stage18'||a==='safeguardingDashboard')return json_({ok:true,data:stage18Dashboard_(pid)});var map={safeguardingPolicies:'SafeguardingPolicies',safeguardingTraining:'SafeguardingTraining',safeguardingRisks:'SafeguardingRisks',protectionCases:'ProtectionCases',referrals:'Referrals',pseaReports:'PSEAReports',feedbackComplaints:'FeedbackComplaints',childConsent:'ChildConsent',safeProgramming:'SafeProgramming',safeguardingIncidents:'SafeguardingIncidents',accountabilityActions:'AccountabilityActions',safeguardingAlerts:'SafeguardingAlerts'},n=map[a];permission_('read',pid);return json_({ok:true,data:s18Rows_(n,pid)});}
function stage18PostAction_(a){return ['stage18Setup','createStage18Record','generateSafeguardingAlerts'].indexOf(a)>=0;}
function stage18Post_(a,d){if(a==='stage18Setup'){permission_('update');return json_({ok:true,message:setupStage18()});}if(a==='createStage18Record')return createStage18Record_(d.entity,d.data||{});if(a==='generateSafeguardingAlerts')return stage18GenerateAlerts_(d.projectId||'');}
