/* UAF STAGE 12 — PROCUREMENT, ASSET & RESOURCE MANAGEMENT M&E */
var STAGE12_HEADERS={
  ProcurementPlans:['Plan ID','Project ID','Grant ID','Procurement Item','Category','Activity ID','Quantity','Estimated Unit Cost','Estimated Total','Procurement Method','Planned Date','Responsible Person','Status','Created At'],
  Procurement:['Procurement ID','Project ID','Grant ID','Plan ID','Date','Item','Category','Activity ID','Supplier','Quantity','Unit Cost','Total Cost','Procurement Method','Purchase Order','Receipt URL','Status','Requested By','Approved By','Created At'],
  Assets:['Asset ID','Project ID','Grant ID','Asset Name','Asset Category','Serial/Tag Number','Purchase Date','Purchase Cost','Currency','Location','Assigned To','Condition','Status','Warranty End','Evidence URL','Created At','Updated At'],
  Inventory:['Inventory ID','Project ID','Item','Category','Unit','Opening Quantity','Received Quantity','Issued Quantity','Balance Quantity','Minimum Level','Location','Responsible Person','Last Updated'],
  AssetMovements:['Movement ID','Asset ID','Project ID','Date','Movement Type','From Location','To Location','From User','To User','Condition','Reason','Approved By','Evidence URL'],
  ResourceUsage:['Usage ID','Project ID','Activity ID','Date','Resource Type','Resource Name','Quantity','Unit','Estimated Cost','Actual Cost','Used By','Purpose','Location','Evidence URL','Recorded By'],
  ProcurementApprovals:['Approval ID','Project ID','Procurement ID','Reviewer','Role','Decision','Comments','Decision Date'],
  ResourceAlerts:['Resource Alert ID','Project ID','Alert Type','Severity','Entity','Record ID','Message','Status','Due Date','Assigned To','Created At']
};
function setupStage12(){var ss=SpreadsheetApp.getActive();Object.keys(STAGE12_HEADERS).forEach(function(n){var s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()==0)s.appendRow(STAGE12_HEADERS[n]);s.setFrozenRows(1);});var s=ss.getSheetByName('Settings');if(s){var old=rows_('Settings');var d={'Stage 12':'Procurement, Asset & Resource Management M&E','Procurement Model':'Plan → Request → Approval → Purchase → Evidence → Verification','Asset Model':'Register → Assign → Move → Maintain → Dispose','Inventory Model':'Opening + Received − Issued = Balance'};Object.keys(d).forEach(function(k){if(!old.some(function(x){return x.Key==k;}))s.appendRow([k,d[k]]);});}return 'Stage 12 setup complete; existing data preserved.';}
function s12n_(v){var n=Number(v);return isNaN(n)?0:n;}
function stage12Visible_(name,pid){return rows_(name).filter(function(x){return !pid||String(x['Project ID'])==String(pid);});}
function stage12Dashboard_(pid){permission_('read',pid||'');var plans=stage12Visible_('ProcurementPlans',pid),proc=stage12Visible_('Procurement',pid),assets=stage12Visible_('Assets',pid),inv=stage12Visible_('Inventory',pid),usage=stage12Visible_('ResourceUsage',pid),alerts=stage12Visible_('ResourceAlerts',pid);var procurementSpend=proc.filter(function(x){return String(x.Status||'').toLowerCase()!=='rejected';}).reduce(function(a,x){return a+s12n_(x['Total Cost']);},0),assetValue=assets.filter(function(x){return String(x.Status||'').toLowerCase()!=='disposed';}).reduce(function(a,x){return a+s12n_(x['Purchase Cost']);},0),openAlerts=alerts.filter(function(x){return String(x.Status||'Open').toLowerCase()!=='resolved';});var lowStock=inv.filter(function(x){return s12n_(x['Balance Quantity'])<=s12n_(x['Minimum Level']);});var pending=proc.filter(function(x){return ['pending','requested'].indexOf(String(x.Status||'').toLowerCase())>=0;});return {summary:{procurementPlans:plans.length,procurementRecords:proc.length,procurementSpend:procurementSpend,activeAssets:assets.filter(function(x){return String(x.Status||'').toLowerCase()!=='disposed';}).length,assetValue:assetValue,inventoryItems:inv.length,lowStockItems:lowStock.length,resourceUsageRecords:usage.length,openAlerts:openAlerts.length,pendingProcurement:pending.length},procurement:proc,assets:assets,inventory:inv,usage:usage,alerts:openAlerts,lowStock:lowStock};}
function createStage12Record_(entity,data){var map={procurementPlan:'ProcurementPlans',procurement:'Procurement',asset:'Assets',inventory:'Inventory',assetMovement:'AssetMovements',resourceUsage:'ResourceUsage',procurementApproval:'ProcurementApprovals',resourceAlert:'ResourceAlerts'},sheet=map[entity];if(!sheet)throw Error('Unsupported Stage 12 entity');var pid=data['Project ID']||data.projectId;permission_('create',pid||'');var s=SpreadsheetApp.getActive().getSheetByName(sheet),h=STAGE12_HEADERS[sheet],now=new Date(),prefix=entity==='asset'?'AST':entity==='procurement'?'PRC':'RES',id=id_(prefix);if((entity==='procurement'||entity==='asset')&&s12n_(data['Total Cost']||data['Purchase Cost']||0)<0)throw Error('Cost cannot be negative.');if(entity==='procurement'&&String(data.Status||'').toLowerCase()==='approved'&&!data['Receipt URL'])throw Error('Approved procurement requires receipt evidence.');s.appendRow(h.map(function(k){if(k==='Created At'||k==='Updated At')return now;if(k.endsWith('ID')||k==='Asset ID'||k==='Procurement ID'||k==='Plan ID'||k==='Inventory ID'||k==='Movement ID'||k==='Usage ID'||k==='Approval ID'||k==='Resource Alert ID')return id;return data[k]!==undefined?data[k]:'';}));audit_('CREATE',entity,id,data);return json_({ok:true,id:id});}
function stage12RefreshInventory_(pid){var inv=stage12Visible_('Inventory',pid),rec=stage12Visible_('ResourceUsage',pid),s=SpreadsheetApp.getActive().getSheetByName('Inventory');var updates=0;inv.forEach(function(i){var id=String(i['Inventory ID']),issued=rec.filter(function(r){return String(r['Resource Name'])===String(i.Item)&&String(r['Resource Type']).toLowerCase()==='inventory';}).reduce(function(a,r){return a+s12n_(r.Quantity);},0);var received=s12n_(i['Received Quantity']),opening=s12n_(i['Opening Quantity']),balance=opening+received-issued;var h=STAGE12_HEADERS.Inventory,vals=s.getRange(2,1,s.getLastRow()-1,h.length).getValues();for(var r=0;r<vals.length;r++){if(String(vals[r][0])===id){s.getRange(r+2,9).setValue(balance);s.getRange(r+2,13).setValue(new Date());updates++;break;}}});return json_({ok:true,updated:updates});}
function stage12GenerateAlerts_(pid){permission_('update',pid||'');var inv=stage12Visible_('Inventory',pid),assets=stage12Visible_('Assets',pid),proc=stage12Visible_('Procurement',pid),s=SpreadsheetApp.getActive().getSheetByName('ResourceAlerts'),created=0;inv.forEach(function(x){if(s12n_(x['Balance Quantity'])<=s12n_(x['Minimum Level'])){s.appendRow([id_('RAL'),new Date(),x['Project ID'],'LOW_STOCK','Inventory',x['Inventory ID'],'Inventory item is at or below minimum level.','Open','',x['Responsible Person'],new Date()]);created++;}});assets.forEach(function(x){var status=String(x.Status||'').toLowerCase();if(status==='lost'||status==='damaged'){s.appendRow([id_('RAL'),new Date(),x['Project ID'],'ASSET_CONDITION','Asset',x['Asset ID'],'Asset requires management attention: '+x.Condition+'.','Open','',x['Assigned To'],new Date()]);created++;}});proc.forEach(function(x){if(String(x.Status||'').toLowerCase()==='approved'&&!x['Receipt URL']){s.appendRow([id_('RAL'),new Date(),x['Project ID'],'MISSING_EVIDENCE','Procurement',x['Procurement ID'],'Approved procurement has no receipt evidence.','Open','',x['Approved By'],new Date()]);created++;}});return json_({ok:true,created:created});}
function stage12GetAction_(a){return ['stage12','resourceDashboard','procurementPlans','procurement','assets','inventory','assetMovements','resourceUsage','procurementApprovals','resourceAlerts'].indexOf(a)>=0;}
function stage12Get_(a,e){var pid=e&&e.parameter?e.parameter.projectId||'':'';if(a==='stage12'||a==='resourceDashboard')return json_({ok:true,data:stage12Dashboard_(pid)});var map={procurementPlans:'ProcurementPlans',procurement:'Procurement',assets:'Assets',inventory:'Inventory',assetMovements:'AssetMovements',resourceUsage:'ResourceUsage',procurementApprovals:'ProcurementApprovals',resourceAlerts:'ResourceAlerts'},n=map[a];permission_('read',pid);return json_({ok:true,data:stage12Visible_(n,pid)});}
function stage12PostAction_(a){return ['stage12Setup','createStage12Record','refreshInventory','generateResourceAlerts'].indexOf(a)>=0;}
function stage12Post_(a,d){if(a==='stage12Setup'){permission_('update');return json_({ok:true,message:setupStage12()});}if(a==='createStage12Record')return createStage12Record_(d.entity,d.data||{});if(a==='refreshInventory')return stage12RefreshInventory_(d.projectId||'');if(a==='generateResourceAlerts')return stage12GenerateAlerts_(d.projectId||'');}
