/* UAF STAGE 15 — PARTNERSHIP, NETWORK & COLLABORATION MANAGEMENT M&E */
var STAGE15_HEADERS={
 Partners:['Partner ID','Organization','Partner Type','County','Community','Contact Person','Email','Phone','Sector','Partnership Status','Relationship Health','Strengths','Capacity Needs','Project Access','Created At','Updated At'],
 MOUs:['MOU ID','Partner ID','Project ID','MOU Title','Start Date','End Date','Scope','Commitments','Status','MOU URL','Review Date','Created At'],
 PartnershipActivities:['Partnership Activity ID','Partner ID','Project ID','Date','Activity','Purpose','Role of Partner','UAF Role','Participants','Output','Outcome','Evidence URL','Status'],
 PartnerContributions:['Contribution ID','Partner ID','Project ID','Date','Contribution Type','Description','Cash Value','In-Kind Value','Currency','Evidence URL','Verified','Status'],
 PartnerReferrals:['Referral ID','Partner ID','Project ID','Beneficiary ID','Date','Referral Type','Reason','Service Referred','Outcome','Follow-up Date','Status'],
 PartnerCommitments:['Commitment ID','Partner ID','Project ID','Date','Commitment','Responsible Person','Due Date','Status','Completion Date','Evidence URL','Notes'],
 PartnerPerformance:['Performance ID','Partner ID','Project ID','Review Period','Deliverables','Achievement','Collaboration Rating','Responsiveness Rating','Quality Rating','Overall Rating','Strengths','Gaps','Recommendation','Reviewer','Review Date'],
 PartnershipMeetings:['Meeting ID','Partner ID','Project ID','Date','Meeting Type','Agenda','Participants','Decisions','Actions','Next Meeting','Evidence URL'],
 JointInitiatives:['Initiative ID','Partner ID','Project ID','Initiative Name','Start Date','End Date','Objective','Target','Achievement','Outcome','Status','Evidence URL'],
 PartnershipRisks:['Risk ID','Partner ID','Project ID','Date','Risk','Likelihood','Impact','Score','Mitigation','Owner','Review Date','Status'],
 PartnershipAlerts:['Alert ID','Partner ID','Project ID','Alert Type','Severity','Message','Status','Due Date','Assigned To','Created At']
};
function setupStage15(){var ss=SpreadsheetApp.getActive();Object.keys(STAGE15_HEADERS).forEach(function(n){var s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()==0)s.appendRow(STAGE15_HEADERS[n]);s.setFrozenRows(1);});var s=ss.getSheetByName('Settings');if(s){var old=rows_('Settings'),d={'Stage 15':'Partnership, Network & Collaboration Management M&E','Partnership Model':'Map → Formalize → Collaborate → Contribute → Review → Sustain','Partner Performance Model':'Commitment → Delivery → Collaboration → Outcome → Learning'};Object.keys(d).forEach(function(k){if(!old.some(function(x){return x.Key==k;}))s.appendRow([k,d[k]]);});}return 'Stage 15 setup complete; existing data preserved.';}
function s15n_(v){var n=Number(v);return isNaN(n)?0:n;}
function s15Rows_(name,pid){return rows_(name).filter(function(x){return !pid||String(x['Project ID']||'')===String(pid);});}
function stage15Dashboard_(pid){permission_('read',pid||'');var p=rows_('Partners'),m=s15Rows_('MOUs',pid),a=s15Rows_('PartnershipActivities',pid),c=s15Rows_('PartnerContributions',pid),r=s15Rows_('PartnerReferrals',pid),cm=s15Rows_('PartnerCommitments',pid),pf=s15Rows_('PartnerPerformance',pid),mt=s15Rows_('PartnershipMeetings',pid),ji=s15Rows_('JointInitiatives',pid),rk=s15Rows_('PartnershipRisks',pid),al=s15Rows_('PartnershipAlerts',pid),now=new Date();var active=p.filter(function(x){return ['active','formal','strategic'].indexOf(String(x['Partnership Status']||'').toLowerCase())>=0;}).length;var exp30=m.filter(function(x){return x['End Date']&&new Date(x['End Date'])>=now&&new Date(x['End Date'])<=new Date(now.getTime()+30*86400000)&&!['completed','closed','inactive'].includes(String(x.Status||'').toLowerCase());}).length;var exp90=m.filter(function(x){return x['End Date']&&new Date(x['End Date'])>=now&&new Date(x['End Date'])<=new Date(now.getTime()+90*86400000)&&!['completed','closed','inactive'].includes(String(x.Status||'').toLowerCase());}).length;var overdue=cm.filter(function(x){return x['Due Date']&&new Date(x['Due Date'])<now&&!['completed','closed'].includes(String(x.Status||'').toLowerCase());});var completed=cm.filter(function(x){return ['completed','closed'].includes(String(x.Status||'').toLowerCase());}).length;var cash=c.reduce(function(x,y){return x+s15n_(y['Cash Value']);},0),inkind=c.reduce(function(x,y){return x+s15n_(y['In-Kind Value']);},0);var avg=pf.length?Math.round(pf.reduce(function(x,y){return x+s15n_(y['Overall Rating']);},0)/pf.length*100)/100:0;return {summary:{partners:p.length,activePartnerships:active,activeMOUs:m.filter(function(x){return ['active','signed','formal'].includes(String(x.Status||'').toLowerCase());}).length,mous:m.length,mousExpiring30:exp30,mousExpiring90:exp90,activities:a.length,contributions:c.length,cashContributions:cash,inKindContributions:inkind,referrals:r.length,commitments:cm.length,completedCommitments:completed,overdueCommitments:overdue.length,performanceReviews:pf.length,averagePartnerRating:avg,meetings:mt.length,jointInitiatives:ji.length,openRisks:rk.filter(function(x){return !['closed','resolved'].includes(String(x.Status||'').toLowerCase());}).length,openAlerts:al.filter(function(x){return !['closed','resolved'].includes(String(x.Status||'').toLowerCase());}).length},partners:p,mous:m,activities:a,contributions:c,referrals:r,commitments:cm,performance:pf,meetings:mt,jointInitiatives:ji,risks:rk,alerts:al.filter(function(x){return !['closed','resolved'].includes(String(x.Status||'').toLowerCase());})};}
function stage15Validate_(entity,d){if(entity==='partner'&&!String(d.Organization||'').trim())throw Error('Partner organization is required.');if(['mou','partnershipActivity','partnerContribution','partnerReferral','partnerCommitment','partnerPerformance','partnershipMeeting','jointInitiative','partnershipRisk'].indexOf(entity)>=0&&!d['Partner ID']&&!d.partnerId)throw Error('Partner ID is required.');if(['mou','partnershipActivity','partnerContribution','partnerReferral','partnerCommitment','partnerPerformance','partnershipMeeting','jointInitiative','partnershipRisk'].indexOf(entity)>=0&&!d['Project ID']&&!d.projectId)throw Error('Project ID is required.');if(entity==='partnerContribution'&&(s15n_(d['Cash Value'])<0||s15n_(d['In-Kind Value'])<0))throw Error('Contribution values cannot be negative.');if(entity==='jointInitiative'&&(s15n_(d.Target)<0||s15n_(d.Achievement)<0))throw Error('Target and achievement cannot be negative.');}
function createStage15Record_(entity,data){var map={partner:'Partners',mou:'MOUs',partnershipActivity:'PartnershipActivities',partnerContribution:'PartnerContributions',partnerReferral:'PartnerReferrals',partnerCommitment:'PartnerCommitments',partnerPerformance:'PartnerPerformance',partnershipMeeting:'PartnershipMeetings',jointInitiative:'JointInitiatives',partnershipRisk:'PartnershipRisks',partnershipAlert:'PartnershipAlerts'},sheet=map[entity];if(!sheet)throw Error('Unsupported Stage 15 entity');var pid=data['Project ID']||data.projectId||'';permission_('create',pid);stage15Validate_(entity,data);var s=SpreadsheetApp.getActive().getSheetByName(sheet),h=STAGE15_HEADERS[sheet],now=new Date(),prefix=entity==='partner'?'PTR':entity==='mou'?'MOU':entity==='partnershipActivity'?'PRA':entity==='partnerContribution'?'CON':entity==='partnerReferral'?'REF':entity==='partnerCommitment'?'PCM':entity==='partnerPerformance'?'PPF':entity==='partnershipMeeting'?'PMT':entity==='jointInitiative'?'JNT':entity==='partnershipRisk'?'PRK':'PAL',id=id_(prefix);s.appendRow(h.map(function(k){if(k==='Created At'||k==='Updated At')return now;if(/ID$/.test(k)&&!data[k])return id;return data[k]!==undefined?data[k]:'';}));audit_('CREATE',entity,id,data);return json_({ok:true,id:id});}
function stage15GenerateAlerts_(pid){permission_('update',pid||'');var s=SpreadsheetApp.getActive().getSheetByName('PartnershipAlerts'),created=0,today=new Date(),cm=s15Rows_('PartnerCommitments',pid),m=s15Rows_('MOUs',pid),rk=s15Rows_('PartnershipRisks',pid);cm.forEach(function(x){if(x['Due Date']&&new Date(x['Due Date'])<today&&!['completed','closed'].includes(String(x.Status||'').toLowerCase())){s.appendRow([id_('PAL'),x['Partner ID'],pid,'COMMITMENT_OVERDUE','High','Partner commitment is overdue: '+x.Commitment,'Open',x['Due Date'],x['Responsible Person'],today]);created++;}});m.forEach(function(x){if(x['End Date']&&new Date(x['End Date'])>=today&&new Date(x['End Date'])<=new Date(today.getTime()+30*86400000)&&!['completed','closed','inactive'].includes(String(x.Status||'').toLowerCase())){s.appendRow([id_('PAL'),x['Partner ID'],pid,'MOU_EXPIRING','High','MOU is expiring within 30 days: '+x['MOU Title'],'Open',x['End Date'],'',today]);created++;}});rk.forEach(function(x){var score=s15n_(x.Score);if(score>=12&&!['closed','resolved'].includes(String(x.Status||'').toLowerCase())){s.appendRow([id_('PAL'),x['Partner ID'],pid,'HIGH_PARTNERSHIP_RISK','High','High partnership risk requires management attention: '+x.Risk,'Open',x['Review Date'],x.Owner,today]);created++;}});return json_({ok:true,created:created});}
function stage15GetAction_(a){return ['stage15','partnershipDashboard','partners','mous','partnershipActivities','partnerContributions','partnerReferrals','partnerCommitments','partnerPerformance','partnershipMeetings','jointInitiatives','partnershipRisks','partnershipAlerts'].indexOf(a)>=0;}
function stage15Get_(a,e){var pid=e&&e.parameter?e.parameter.projectId||'':'';if(a==='stage15'||a==='partnershipDashboard')return json_({ok:true,data:stage15Dashboard_(pid)});var map={partners:'Partners',mous:'MOUs',partnershipActivities:'PartnershipActivities',partnerContributions:'PartnerContributions',partnerReferrals:'PartnerReferrals',partnerCommitments:'PartnerCommitments',partnerPerformance:'PartnerPerformance',partnershipMeetings:'PartnershipMeetings',jointInitiatives:'JointInitiatives',partnershipRisks:'PartnershipRisks',partnershipAlerts:'PartnershipAlerts'},n=map[a];permission_('read',pid);return json_({ok:true,data:s15Rows_(n,pid)});}
function stage15PostAction_(a){return ['stage15Setup','createStage15Record','generatePartnershipAlerts'].indexOf(a)>=0;}
function stage15Post_(a,d){if(a==='stage15Setup'){permission_('update');return json_({ok:true,message:setupStage15()});}if(a==='createStage15Record')return createStage15Record_(d.entity,d.data||{});if(a==='generatePartnershipAlerts')return stage15GenerateAlerts_(d.projectId||'');}
